// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core_support.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

/**
 * Protobuf enum {@code proto.renderprotocol.ui.v1.RPAlignment}
 */
@com.google.protobuf.Generated
public enum RPAlignment
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RP_ALIGNMENT_UNSPECIFIED = 0;</code>
   */
  RP_ALIGNMENT_UNSPECIFIED(0),
  /**
   * <code>RP_ALIGNMENT_CENTER = 1;</code>
   */
  RP_ALIGNMENT_CENTER(1),
  /**
   * <code>RP_ALIGNMENT_TOP = 2;</code>
   */
  RP_ALIGNMENT_TOP(2),
  /**
   * <code>RP_ALIGNMENT_BOTTOM = 3;</code>
   */
  RP_ALIGNMENT_BOTTOM(3),
  /**
   * <code>RP_ALIGNMENT_LEADING = 4;</code>
   */
  RP_ALIGNMENT_LEADING(4),
  /**
   * <code>RP_ALIGNMENT_TRAILING = 5;</code>
   */
  RP_ALIGNMENT_TRAILING(5),
  /**
   * <code>RP_ALIGNMENT_TOP_LEADING = 6;</code>
   */
  RP_ALIGNMENT_TOP_LEADING(6),
  /**
   * <code>RP_ALIGNMENT_TOP_TRAILING = 7;</code>
   */
  RP_ALIGNMENT_TOP_TRAILING(7),
  /**
   * <code>RP_ALIGNMENT_BOTTOM_LEADING = 8;</code>
   */
  RP_ALIGNMENT_BOTTOM_LEADING(8),
  /**
   * <code>RP_ALIGNMENT_BOTTOM_TRAILING = 9;</code>
   */
  RP_ALIGNMENT_BOTTOM_TRAILING(9),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPAlignment");
  }
  /**
   * <code>RP_ALIGNMENT_UNSPECIFIED = 0;</code>
   */
  public static final int RP_ALIGNMENT_UNSPECIFIED_VALUE = 0;
  /**
   * <code>RP_ALIGNMENT_CENTER = 1;</code>
   */
  public static final int RP_ALIGNMENT_CENTER_VALUE = 1;
  /**
   * <code>RP_ALIGNMENT_TOP = 2;</code>
   */
  public static final int RP_ALIGNMENT_TOP_VALUE = 2;
  /**
   * <code>RP_ALIGNMENT_BOTTOM = 3;</code>
   */
  public static final int RP_ALIGNMENT_BOTTOM_VALUE = 3;
  /**
   * <code>RP_ALIGNMENT_LEADING = 4;</code>
   */
  public static final int RP_ALIGNMENT_LEADING_VALUE = 4;
  /**
   * <code>RP_ALIGNMENT_TRAILING = 5;</code>
   */
  public static final int RP_ALIGNMENT_TRAILING_VALUE = 5;
  /**
   * <code>RP_ALIGNMENT_TOP_LEADING = 6;</code>
   */
  public static final int RP_ALIGNMENT_TOP_LEADING_VALUE = 6;
  /**
   * <code>RP_ALIGNMENT_TOP_TRAILING = 7;</code>
   */
  public static final int RP_ALIGNMENT_TOP_TRAILING_VALUE = 7;
  /**
   * <code>RP_ALIGNMENT_BOTTOM_LEADING = 8;</code>
   */
  public static final int RP_ALIGNMENT_BOTTOM_LEADING_VALUE = 8;
  /**
   * <code>RP_ALIGNMENT_BOTTOM_TRAILING = 9;</code>
   */
  public static final int RP_ALIGNMENT_BOTTOM_TRAILING_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RPAlignment valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RPAlignment forNumber(int value) {
    switch (value) {
      case 0: return RP_ALIGNMENT_UNSPECIFIED;
      case 1: return RP_ALIGNMENT_CENTER;
      case 2: return RP_ALIGNMENT_TOP;
      case 3: return RP_ALIGNMENT_BOTTOM;
      case 4: return RP_ALIGNMENT_LEADING;
      case 5: return RP_ALIGNMENT_TRAILING;
      case 6: return RP_ALIGNMENT_TOP_LEADING;
      case 7: return RP_ALIGNMENT_TOP_TRAILING;
      case 8: return RP_ALIGNMENT_BOTTOM_LEADING;
      case 9: return RP_ALIGNMENT_BOTTOM_TRAILING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RPAlignment>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RPAlignment> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RPAlignment>() {
          public RPAlignment findValueByNumber(int number) {
            return RPAlignment.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.getDescriptor().getEnumType(0);
  }

  private static final RPAlignment[] VALUES = values();

  public static RPAlignment valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RPAlignment(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.renderprotocol.ui.v1.RPAlignment)
}

