// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPAspectRatio")
public inline fun rPAspectRatio(block: com.nukive.renderprotocol.ui.v1.RPAspectRatioKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPAspectRatio =
  com.nukive.renderprotocol.ui.v1.RPAspectRatioKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPAspectRatio.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPAspectRatio`
 */
public object RPAspectRatioKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPAspectRatio.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPAspectRatio.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPAspectRatio = _builder.build()

    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     */
    public var child: com.nukive.renderprotocol.ui.v1.RPWidget
      @kotlin.jvm.JvmName("getChild")
        get() = _builder.child
      @kotlin.jvm.JvmName("setChild")
        set(value) {
        _builder.child = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     */
    public fun clearChild() {
      _builder.clearChild()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     * @return Whether the child field is set.
     */
    public fun hasChild(): kotlin.Boolean {
      return _builder.hasChild()
    }

    public val RPAspectRatioKt.Dsl.childOrNull: com.nukive.renderprotocol.ui.v1.RPWidget?
      get() = _builder.childOrNull

    /**
     * `float ratio = 2 [json_name = "ratio"];`
     */
    public var ratio: kotlin.Float
      @kotlin.jvm.JvmName("getRatio")
        get() = _builder.ratio
      @kotlin.jvm.JvmName("setRatio")
        set(value) {
        _builder.ratio = value
      }
    /**
     * `float ratio = 2 [json_name = "ratio"];`
     */
    public fun clearRatio() {
      _builder.clearRatio()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPContentMode content_mode = 3 [json_name = "contentMode"];`
     */
    public var contentMode: com.nukive.renderprotocol.ui.v1.RPContentMode
      @kotlin.jvm.JvmName("getContentMode")
        get() = _builder.contentMode
      @kotlin.jvm.JvmName("setContentMode")
        set(value) {
        _builder.contentMode = value
      }
    public var contentModeValue: kotlin.Int
      @kotlin.jvm.JvmName("getContentModeValue")
        get() = _builder.contentModeValue
      @kotlin.jvm.JvmName("setContentModeValue")
        set(value) {
        _builder.contentModeValue = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPContentMode content_mode = 3 [json_name = "contentMode"];`
     */
    public fun clearContentMode() {
      _builder.clearContentMode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPAspectRatio.copy(block: `com.nukive.renderprotocol.ui.v1`.RPAspectRatioKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPAspectRatio =
  `com.nukive.renderprotocol.ui.v1`.RPAspectRatioKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPAspectRatioOrBuilder.childOrNull: com.nukive.renderprotocol.ui.v1.RPWidget?
  get() = if (hasChild()) getChild() else null

