// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_bottom_nav_bar.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

/**
 * Protobuf type {@code proto.renderprotocol.ui.v1.RPBottomNavItem}
 */
@com.google.protobuf.Generated
public final class RPBottomNavItem extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.renderprotocol.ui.v1.RPBottomNavItem)
    RPBottomNavItemOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPBottomNavItem");
  }
  // Use RPBottomNavItem.newBuilder() to construct.
  private RPBottomNavItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPBottomNavItem() {
    label_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavItem_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nukive.renderprotocol.ui.v1.RPBottomNavItem.class, com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder.class);
  }

  private int bitField0_;
  public static final int ICON_FIELD_NUMBER = 1;
  private com.nukive.renderprotocol.ui.v1.RPIcon icon_;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
   * @return Whether the icon field is set.
   */
  @java.lang.Override
  public boolean hasIcon() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
   * @return The icon.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPIcon getIcon() {
    return icon_ == null ? com.nukive.renderprotocol.ui.v1.RPIcon.getDefaultInstance() : icon_;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPIconOrBuilder getIconOrBuilder() {
    return icon_ == null ? com.nukive.renderprotocol.ui.v1.RPIcon.getDefaultInstance() : icon_;
  }

  public static final int LABEL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object label_ = "";
  /**
   * <code>optional string label = 2 [json_name = "label"];</code>
   * @return Whether the label field is set.
   */
  @java.lang.Override
  public boolean hasLabel() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string label = 2 [json_name = "label"];</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>optional string label = 2 [json_name = "label"];</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 3;
  private com.nukive.renderprotocol.ui.v1.RPAction action_;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
   * @return Whether the action field is set.
   */
  @java.lang.Override
  public boolean hasAction() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
   * @return The action.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPAction getAction() {
    return action_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : action_;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getActionOrBuilder() {
    return action_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : action_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getIcon());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, label_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getAction());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIcon());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, label_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAction());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nukive.renderprotocol.ui.v1.RPBottomNavItem)) {
      return super.equals(obj);
    }
    com.nukive.renderprotocol.ui.v1.RPBottomNavItem other = (com.nukive.renderprotocol.ui.v1.RPBottomNavItem) obj;

    if (hasIcon() != other.hasIcon()) return false;
    if (hasIcon()) {
      if (!getIcon()
          .equals(other.getIcon())) return false;
    }
    if (hasLabel() != other.hasLabel()) return false;
    if (hasLabel()) {
      if (!getLabel()
          .equals(other.getLabel())) return false;
    }
    if (hasAction() != other.hasAction()) return false;
    if (hasAction()) {
      if (!getAction()
          .equals(other.getAction())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIcon()) {
      hash = (37 * hash) + ICON_FIELD_NUMBER;
      hash = (53 * hash) + getIcon().hashCode();
    }
    if (hasLabel()) {
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
    }
    if (hasAction()) {
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nukive.renderprotocol.ui.v1.RPBottomNavItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.renderprotocol.ui.v1.RPBottomNavItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.renderprotocol.ui.v1.RPBottomNavItem)
      com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nukive.renderprotocol.ui.v1.RPBottomNavItem.class, com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder.class);
    }

    // Construct using com.nukive.renderprotocol.ui.v1.RPBottomNavItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetIconFieldBuilder();
        internalGetActionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      icon_ = null;
      if (iconBuilder_ != null) {
        iconBuilder_.dispose();
        iconBuilder_ = null;
      }
      label_ = "";
      action_ = null;
      if (actionBuilder_ != null) {
        actionBuilder_.dispose();
        actionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavItem_descriptor;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPBottomNavItem getDefaultInstanceForType() {
      return com.nukive.renderprotocol.ui.v1.RPBottomNavItem.getDefaultInstance();
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPBottomNavItem build() {
      com.nukive.renderprotocol.ui.v1.RPBottomNavItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPBottomNavItem buildPartial() {
      com.nukive.renderprotocol.ui.v1.RPBottomNavItem result = new com.nukive.renderprotocol.ui.v1.RPBottomNavItem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nukive.renderprotocol.ui.v1.RPBottomNavItem result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.icon_ = iconBuilder_ == null
            ? icon_
            : iconBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.label_ = label_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.action_ = actionBuilder_ == null
            ? action_
            : actionBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nukive.renderprotocol.ui.v1.RPBottomNavItem) {
        return mergeFrom((com.nukive.renderprotocol.ui.v1.RPBottomNavItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nukive.renderprotocol.ui.v1.RPBottomNavItem other) {
      if (other == com.nukive.renderprotocol.ui.v1.RPBottomNavItem.getDefaultInstance()) return this;
      if (other.hasIcon()) {
        mergeIcon(other.getIcon());
      }
      if (other.hasLabel()) {
        label_ = other.label_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasAction()) {
        mergeAction(other.getAction());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetIconFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              label_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetActionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.nukive.renderprotocol.ui.v1.RPIcon icon_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPIcon, com.nukive.renderprotocol.ui.v1.RPIcon.Builder, com.nukive.renderprotocol.ui.v1.RPIconOrBuilder> iconBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     * @return Whether the icon field is set.
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     * @return The icon.
     */
    public com.nukive.renderprotocol.ui.v1.RPIcon getIcon() {
      if (iconBuilder_ == null) {
        return icon_ == null ? com.nukive.renderprotocol.ui.v1.RPIcon.getDefaultInstance() : icon_;
      } else {
        return iconBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     */
    public Builder setIcon(com.nukive.renderprotocol.ui.v1.RPIcon value) {
      if (iconBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        icon_ = value;
      } else {
        iconBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     */
    public Builder setIcon(
        com.nukive.renderprotocol.ui.v1.RPIcon.Builder builderForValue) {
      if (iconBuilder_ == null) {
        icon_ = builderForValue.build();
      } else {
        iconBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     */
    public Builder mergeIcon(com.nukive.renderprotocol.ui.v1.RPIcon value) {
      if (iconBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          icon_ != null &&
          icon_ != com.nukive.renderprotocol.ui.v1.RPIcon.getDefaultInstance()) {
          getIconBuilder().mergeFrom(value);
        } else {
          icon_ = value;
        }
      } else {
        iconBuilder_.mergeFrom(value);
      }
      if (icon_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     */
    public Builder clearIcon() {
      bitField0_ = (bitField0_ & ~0x00000001);
      icon_ = null;
      if (iconBuilder_ != null) {
        iconBuilder_.dispose();
        iconBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPIcon.Builder getIconBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetIconFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPIconOrBuilder getIconOrBuilder() {
      if (iconBuilder_ != null) {
        return iconBuilder_.getMessageOrBuilder();
      } else {
        return icon_ == null ?
            com.nukive.renderprotocol.ui.v1.RPIcon.getDefaultInstance() : icon_;
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPIcon, com.nukive.renderprotocol.ui.v1.RPIcon.Builder, com.nukive.renderprotocol.ui.v1.RPIconOrBuilder> 
        internalGetIconFieldBuilder() {
      if (iconBuilder_ == null) {
        iconBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPIcon, com.nukive.renderprotocol.ui.v1.RPIcon.Builder, com.nukive.renderprotocol.ui.v1.RPIconOrBuilder>(
                getIcon(),
                getParentForChildren(),
                isClean());
        icon_ = null;
      }
      return iconBuilder_;
    }

    private java.lang.Object label_ = "";
    /**
     * <code>optional string label = 2 [json_name = "label"];</code>
     * @return Whether the label field is set.
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string label = 2 [json_name = "label"];</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string label = 2 [json_name = "label"];</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string label = 2 [json_name = "label"];</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      label_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string label = 2 [json_name = "label"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      label_ = getDefaultInstance().getLabel();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string label = 2 [json_name = "label"];</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      label_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.nukive.renderprotocol.ui.v1.RPAction action_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder> actionBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     * @return Whether the action field is set.
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     * @return The action.
     */
    public com.nukive.renderprotocol.ui.v1.RPAction getAction() {
      if (actionBuilder_ == null) {
        return action_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : action_;
      } else {
        return actionBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     */
    public Builder setAction(com.nukive.renderprotocol.ui.v1.RPAction value) {
      if (actionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        action_ = value;
      } else {
        actionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     */
    public Builder setAction(
        com.nukive.renderprotocol.ui.v1.RPAction.Builder builderForValue) {
      if (actionBuilder_ == null) {
        action_ = builderForValue.build();
      } else {
        actionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     */
    public Builder mergeAction(com.nukive.renderprotocol.ui.v1.RPAction value) {
      if (actionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          action_ != null &&
          action_ != com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance()) {
          getActionBuilder().mergeFrom(value);
        } else {
          action_ = value;
        }
      } else {
        actionBuilder_.mergeFrom(value);
      }
      if (action_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000004);
      action_ = null;
      if (actionBuilder_ != null) {
        actionBuilder_.dispose();
        actionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPAction.Builder getActionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getActionOrBuilder() {
      if (actionBuilder_ != null) {
        return actionBuilder_.getMessageOrBuilder();
      } else {
        return action_ == null ?
            com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : action_;
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder> 
        internalGetActionFieldBuilder() {
      if (actionBuilder_ == null) {
        actionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder>(
                getAction(),
                getParentForChildren(),
                isClean());
        action_ = null;
      }
      return actionBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.renderprotocol.ui.v1.RPBottomNavItem)
  }

  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPBottomNavItem)
  private static final com.nukive.renderprotocol.ui.v1.RPBottomNavItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nukive.renderprotocol.ui.v1.RPBottomNavItem();
  }

  public static com.nukive.renderprotocol.ui.v1.RPBottomNavItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPBottomNavItem>
      PARSER = new com.google.protobuf.AbstractParser<RPBottomNavItem>() {
    @java.lang.Override
    public RPBottomNavItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPBottomNavItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPBottomNavItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPBottomNavItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

