// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_bottom_nav_bar.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPBottomNavItem")
public inline fun rPBottomNavItem(block: com.nukive.renderprotocol.ui.v1.RPBottomNavItemKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPBottomNavItem =
  com.nukive.renderprotocol.ui.v1.RPBottomNavItemKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPBottomNavItem.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPBottomNavItem`
 */
public object RPBottomNavItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPBottomNavItem = _builder.build()

    /**
     * `.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];`
     */
    public var icon: com.nukive.renderprotocol.ui.v1.RPIcon
      @kotlin.jvm.JvmName("getIcon")
        get() = _builder.icon
      @kotlin.jvm.JvmName("setIcon")
        set(value) {
        _builder.icon = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];`
     */
    public fun clearIcon() {
      _builder.clearIcon()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];`
     * @return Whether the icon field is set.
     */
    public fun hasIcon(): kotlin.Boolean {
      return _builder.hasIcon()
    }

    public val RPBottomNavItemKt.Dsl.iconOrNull: com.nukive.renderprotocol.ui.v1.RPIcon?
      get() = _builder.iconOrNull

    /**
     * `optional string label = 2 [json_name = "label"];`
     */
    public var label: kotlin.String
      @kotlin.jvm.JvmName("getLabel")
        get() = _builder.label
      @kotlin.jvm.JvmName("setLabel")
        set(value) {
        _builder.label = value
      }
    /**
     * `optional string label = 2 [json_name = "label"];`
     */
    public fun clearLabel() {
      _builder.clearLabel()
    }
    /**
     * `optional string label = 2 [json_name = "label"];`
     * @return Whether the label field is set.
     */
    public fun hasLabel(): kotlin.Boolean {
      return _builder.hasLabel()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];`
     */
    public var action: com.nukive.renderprotocol.ui.v1.RPAction
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];`
     */
    public fun clearAction() {
      _builder.clearAction()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];`
     * @return Whether the action field is set.
     */
    public fun hasAction(): kotlin.Boolean {
      return _builder.hasAction()
    }

    public val RPBottomNavItemKt.Dsl.actionOrNull: com.nukive.renderprotocol.ui.v1.RPAction?
      get() = _builder.actionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPBottomNavItem.copy(block: `com.nukive.renderprotocol.ui.v1`.RPBottomNavItemKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPBottomNavItem =
  `com.nukive.renderprotocol.ui.v1`.RPBottomNavItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder.iconOrNull: com.nukive.renderprotocol.ui.v1.RPIcon?
  get() = if (hasIcon()) getIcon() else null

public val com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder.actionOrNull: com.nukive.renderprotocol.ui.v1.RPAction?
  get() = if (hasAction()) getAction() else null

