// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_bottom_nav_bar.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

/**
 * Protobuf type {@code proto.renderprotocol.ui.v1.RPBottomNavBar}
 */
@com.google.protobuf.Generated
public final class RPBottomNavBar extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.renderprotocol.ui.v1.RPBottomNavBar)
    RPBottomNavBarOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPBottomNavBar");
  }
  // Use RPBottomNavBar.newBuilder() to construct.
  private RPBottomNavBar(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPBottomNavBar() {
    items_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavBar_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavBar_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavBar_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nukive.renderprotocol.ui.v1.RPBottomNavBar.class, com.nukive.renderprotocol.ui.v1.RPBottomNavBar.Builder.class);
  }

  private int bitField0_;
  public static final int ITEMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.nukive.renderprotocol.ui.v1.RPBottomNavItem> items_;
  /**
   * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public java.util.List<com.nukive.renderprotocol.ui.v1.RPBottomNavItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPBottomNavItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int SELECTED_INDEX_FIELD_NUMBER = 2;
  private int selectedIndex_ = 0;
  /**
   * <code>optional int32 selected_index = 2 [json_name = "selectedIndex"];</code>
   * @return Whether the selectedIndex field is set.
   */
  @java.lang.Override
  public boolean hasSelectedIndex() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 selected_index = 2 [json_name = "selectedIndex"];</code>
   * @return The selectedIndex.
   */
  @java.lang.Override
  public int getSelectedIndex() {
    return selectedIndex_;
  }

  public static final int BACKGROUND_COLOR_FIELD_NUMBER = 3;
  private com.nukive.renderprotocol.ui.v1.RPColor backgroundColor_;
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
   * @return Whether the backgroundColor field is set.
   */
  @java.lang.Override
  public boolean hasBackgroundColor() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
   * @return The backgroundColor.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPColor getBackgroundColor() {
    return backgroundColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : backgroundColor_;
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPColorOrBuilder getBackgroundColorOrBuilder() {
    return backgroundColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : backgroundColor_;
  }

  public static final int SELECTED_COLOR_FIELD_NUMBER = 4;
  private com.nukive.renderprotocol.ui.v1.RPColor selectedColor_;
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
   * @return Whether the selectedColor field is set.
   */
  @java.lang.Override
  public boolean hasSelectedColor() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
   * @return The selectedColor.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPColor getSelectedColor() {
    return selectedColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : selectedColor_;
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPColorOrBuilder getSelectedColorOrBuilder() {
    return selectedColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : selectedColor_;
  }

  public static final int UNSELECTED_COLOR_FIELD_NUMBER = 5;
  private com.nukive.renderprotocol.ui.v1.RPColor unselectedColor_;
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
   * @return Whether the unselectedColor field is set.
   */
  @java.lang.Override
  public boolean hasUnselectedColor() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
   * @return The unselectedColor.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPColor getUnselectedColor() {
    return unselectedColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : unselectedColor_;
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPColorOrBuilder getUnselectedColorOrBuilder() {
    return unselectedColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : unselectedColor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, selectedIndex_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getBackgroundColor());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getSelectedColor());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(5, getUnselectedColor());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = items_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(items_.get(i));
          }
          size += 1 * count;
        }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, selectedIndex_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBackgroundColor());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSelectedColor());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getUnselectedColor());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nukive.renderprotocol.ui.v1.RPBottomNavBar)) {
      return super.equals(obj);
    }
    com.nukive.renderprotocol.ui.v1.RPBottomNavBar other = (com.nukive.renderprotocol.ui.v1.RPBottomNavBar) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (hasSelectedIndex() != other.hasSelectedIndex()) return false;
    if (hasSelectedIndex()) {
      if (getSelectedIndex()
          != other.getSelectedIndex()) return false;
    }
    if (hasBackgroundColor() != other.hasBackgroundColor()) return false;
    if (hasBackgroundColor()) {
      if (!getBackgroundColor()
          .equals(other.getBackgroundColor())) return false;
    }
    if (hasSelectedColor() != other.hasSelectedColor()) return false;
    if (hasSelectedColor()) {
      if (!getSelectedColor()
          .equals(other.getSelectedColor())) return false;
    }
    if (hasUnselectedColor() != other.hasUnselectedColor()) return false;
    if (hasUnselectedColor()) {
      if (!getUnselectedColor()
          .equals(other.getUnselectedColor())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    if (hasSelectedIndex()) {
      hash = (37 * hash) + SELECTED_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getSelectedIndex();
    }
    if (hasBackgroundColor()) {
      hash = (37 * hash) + BACKGROUND_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getBackgroundColor().hashCode();
    }
    if (hasSelectedColor()) {
      hash = (37 * hash) + SELECTED_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getSelectedColor().hashCode();
    }
    if (hasUnselectedColor()) {
      hash = (37 * hash) + UNSELECTED_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getUnselectedColor().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nukive.renderprotocol.ui.v1.RPBottomNavBar prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.renderprotocol.ui.v1.RPBottomNavBar}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.renderprotocol.ui.v1.RPBottomNavBar)
      com.nukive.renderprotocol.ui.v1.RPBottomNavBarOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavBar_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavBar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nukive.renderprotocol.ui.v1.RPBottomNavBar.class, com.nukive.renderprotocol.ui.v1.RPBottomNavBar.Builder.class);
    }

    // Construct using com.nukive.renderprotocol.ui.v1.RPBottomNavBar.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetItemsFieldBuilder();
        internalGetBackgroundColorFieldBuilder();
        internalGetSelectedColorFieldBuilder();
        internalGetUnselectedColorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      selectedIndex_ = 0;
      backgroundColor_ = null;
      if (backgroundColorBuilder_ != null) {
        backgroundColorBuilder_.dispose();
        backgroundColorBuilder_ = null;
      }
      selectedColor_ = null;
      if (selectedColorBuilder_ != null) {
        selectedColorBuilder_.dispose();
        selectedColorBuilder_ = null;
      }
      unselectedColor_ = null;
      if (unselectedColorBuilder_ != null) {
        unselectedColorBuilder_.dispose();
        unselectedColorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.internal_static_proto_renderprotocol_ui_v1_RPBottomNavBar_descriptor;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPBottomNavBar getDefaultInstanceForType() {
      return com.nukive.renderprotocol.ui.v1.RPBottomNavBar.getDefaultInstance();
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPBottomNavBar build() {
      com.nukive.renderprotocol.ui.v1.RPBottomNavBar result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPBottomNavBar buildPartial() {
      com.nukive.renderprotocol.ui.v1.RPBottomNavBar result = new com.nukive.renderprotocol.ui.v1.RPBottomNavBar(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.nukive.renderprotocol.ui.v1.RPBottomNavBar result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(com.nukive.renderprotocol.ui.v1.RPBottomNavBar result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.selectedIndex_ = selectedIndex_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.backgroundColor_ = backgroundColorBuilder_ == null
            ? backgroundColor_
            : backgroundColorBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.selectedColor_ = selectedColorBuilder_ == null
            ? selectedColor_
            : selectedColorBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.unselectedColor_ = unselectedColorBuilder_ == null
            ? unselectedColor_
            : unselectedColorBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nukive.renderprotocol.ui.v1.RPBottomNavBar) {
        return mergeFrom((com.nukive.renderprotocol.ui.v1.RPBottomNavBar)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nukive.renderprotocol.ui.v1.RPBottomNavBar other) {
      if (other == com.nukive.renderprotocol.ui.v1.RPBottomNavBar.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.hasSelectedIndex()) {
        setSelectedIndex(other.getSelectedIndex());
      }
      if (other.hasBackgroundColor()) {
        mergeBackgroundColor(other.getBackgroundColor());
      }
      if (other.hasSelectedColor()) {
        mergeSelectedColor(other.getSelectedColor());
      }
      if (other.hasUnselectedColor()) {
        mergeUnselectedColor(other.getUnselectedColor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.nukive.renderprotocol.ui.v1.RPBottomNavItem m =
                  input.readMessage(
                      com.nukive.renderprotocol.ui.v1.RPBottomNavItem.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              selectedIndex_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  internalGetBackgroundColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetSelectedColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetUnselectedColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.nukive.renderprotocol.ui.v1.RPBottomNavItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.nukive.renderprotocol.ui.v1.RPBottomNavItem>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPBottomNavItem, com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder, com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public java.util.List<com.nukive.renderprotocol.ui.v1.RPBottomNavItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPBottomNavItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder setItems(
        int index, com.nukive.renderprotocol.ui.v1.RPBottomNavItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder setItems(
        int index, com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder addItems(com.nukive.renderprotocol.ui.v1.RPBottomNavItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder addItems(
        int index, com.nukive.renderprotocol.ui.v1.RPBottomNavItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder addItems(
        com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder addItems(
        int index, com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.nukive.renderprotocol.ui.v1.RPBottomNavItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder getItemsBuilder(
        int index) {
      return internalGetItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public java.util.List<? extends com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder addItemsBuilder() {
      return internalGetItemsFieldBuilder().addBuilder(
          com.nukive.renderprotocol.ui.v1.RPBottomNavItem.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder addItemsBuilder(
        int index) {
      return internalGetItemsFieldBuilder().addBuilder(
          index, com.nukive.renderprotocol.ui.v1.RPBottomNavItem.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];</code>
     */
    public java.util.List<com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder> 
         getItemsBuilderList() {
      return internalGetItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPBottomNavItem, com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder, com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder> 
        internalGetItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPBottomNavItem, com.nukive.renderprotocol.ui.v1.RPBottomNavItem.Builder, com.nukive.renderprotocol.ui.v1.RPBottomNavItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private int selectedIndex_ ;
    /**
     * <code>optional int32 selected_index = 2 [json_name = "selectedIndex"];</code>
     * @return Whether the selectedIndex field is set.
     */
    @java.lang.Override
    public boolean hasSelectedIndex() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 selected_index = 2 [json_name = "selectedIndex"];</code>
     * @return The selectedIndex.
     */
    @java.lang.Override
    public int getSelectedIndex() {
      return selectedIndex_;
    }
    /**
     * <code>optional int32 selected_index = 2 [json_name = "selectedIndex"];</code>
     * @param value The selectedIndex to set.
     * @return This builder for chaining.
     */
    public Builder setSelectedIndex(int value) {

      selectedIndex_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 selected_index = 2 [json_name = "selectedIndex"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSelectedIndex() {
      bitField0_ = (bitField0_ & ~0x00000002);
      selectedIndex_ = 0;
      onChanged();
      return this;
    }

    private com.nukive.renderprotocol.ui.v1.RPColor backgroundColor_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder> backgroundColorBuilder_;
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     * @return Whether the backgroundColor field is set.
     */
    public boolean hasBackgroundColor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     * @return The backgroundColor.
     */
    public com.nukive.renderprotocol.ui.v1.RPColor getBackgroundColor() {
      if (backgroundColorBuilder_ == null) {
        return backgroundColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : backgroundColor_;
      } else {
        return backgroundColorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     */
    public Builder setBackgroundColor(com.nukive.renderprotocol.ui.v1.RPColor value) {
      if (backgroundColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        backgroundColor_ = value;
      } else {
        backgroundColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     */
    public Builder setBackgroundColor(
        com.nukive.renderprotocol.ui.v1.RPColor.Builder builderForValue) {
      if (backgroundColorBuilder_ == null) {
        backgroundColor_ = builderForValue.build();
      } else {
        backgroundColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     */
    public Builder mergeBackgroundColor(com.nukive.renderprotocol.ui.v1.RPColor value) {
      if (backgroundColorBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          backgroundColor_ != null &&
          backgroundColor_ != com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance()) {
          getBackgroundColorBuilder().mergeFrom(value);
        } else {
          backgroundColor_ = value;
        }
      } else {
        backgroundColorBuilder_.mergeFrom(value);
      }
      if (backgroundColor_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     */
    public Builder clearBackgroundColor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      backgroundColor_ = null;
      if (backgroundColorBuilder_ != null) {
        backgroundColorBuilder_.dispose();
        backgroundColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPColor.Builder getBackgroundColorBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetBackgroundColorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPColorOrBuilder getBackgroundColorOrBuilder() {
      if (backgroundColorBuilder_ != null) {
        return backgroundColorBuilder_.getMessageOrBuilder();
      } else {
        return backgroundColor_ == null ?
            com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : backgroundColor_;
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder> 
        internalGetBackgroundColorFieldBuilder() {
      if (backgroundColorBuilder_ == null) {
        backgroundColorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder>(
                getBackgroundColor(),
                getParentForChildren(),
                isClean());
        backgroundColor_ = null;
      }
      return backgroundColorBuilder_;
    }

    private com.nukive.renderprotocol.ui.v1.RPColor selectedColor_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder> selectedColorBuilder_;
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     * @return Whether the selectedColor field is set.
     */
    public boolean hasSelectedColor() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     * @return The selectedColor.
     */
    public com.nukive.renderprotocol.ui.v1.RPColor getSelectedColor() {
      if (selectedColorBuilder_ == null) {
        return selectedColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : selectedColor_;
      } else {
        return selectedColorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     */
    public Builder setSelectedColor(com.nukive.renderprotocol.ui.v1.RPColor value) {
      if (selectedColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        selectedColor_ = value;
      } else {
        selectedColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     */
    public Builder setSelectedColor(
        com.nukive.renderprotocol.ui.v1.RPColor.Builder builderForValue) {
      if (selectedColorBuilder_ == null) {
        selectedColor_ = builderForValue.build();
      } else {
        selectedColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     */
    public Builder mergeSelectedColor(com.nukive.renderprotocol.ui.v1.RPColor value) {
      if (selectedColorBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          selectedColor_ != null &&
          selectedColor_ != com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance()) {
          getSelectedColorBuilder().mergeFrom(value);
        } else {
          selectedColor_ = value;
        }
      } else {
        selectedColorBuilder_.mergeFrom(value);
      }
      if (selectedColor_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     */
    public Builder clearSelectedColor() {
      bitField0_ = (bitField0_ & ~0x00000008);
      selectedColor_ = null;
      if (selectedColorBuilder_ != null) {
        selectedColorBuilder_.dispose();
        selectedColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPColor.Builder getSelectedColorBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetSelectedColorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPColorOrBuilder getSelectedColorOrBuilder() {
      if (selectedColorBuilder_ != null) {
        return selectedColorBuilder_.getMessageOrBuilder();
      } else {
        return selectedColor_ == null ?
            com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : selectedColor_;
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder> 
        internalGetSelectedColorFieldBuilder() {
      if (selectedColorBuilder_ == null) {
        selectedColorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder>(
                getSelectedColor(),
                getParentForChildren(),
                isClean());
        selectedColor_ = null;
      }
      return selectedColorBuilder_;
    }

    private com.nukive.renderprotocol.ui.v1.RPColor unselectedColor_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder> unselectedColorBuilder_;
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     * @return Whether the unselectedColor field is set.
     */
    public boolean hasUnselectedColor() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     * @return The unselectedColor.
     */
    public com.nukive.renderprotocol.ui.v1.RPColor getUnselectedColor() {
      if (unselectedColorBuilder_ == null) {
        return unselectedColor_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : unselectedColor_;
      } else {
        return unselectedColorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     */
    public Builder setUnselectedColor(com.nukive.renderprotocol.ui.v1.RPColor value) {
      if (unselectedColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unselectedColor_ = value;
      } else {
        unselectedColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     */
    public Builder setUnselectedColor(
        com.nukive.renderprotocol.ui.v1.RPColor.Builder builderForValue) {
      if (unselectedColorBuilder_ == null) {
        unselectedColor_ = builderForValue.build();
      } else {
        unselectedColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     */
    public Builder mergeUnselectedColor(com.nukive.renderprotocol.ui.v1.RPColor value) {
      if (unselectedColorBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          unselectedColor_ != null &&
          unselectedColor_ != com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance()) {
          getUnselectedColorBuilder().mergeFrom(value);
        } else {
          unselectedColor_ = value;
        }
      } else {
        unselectedColorBuilder_.mergeFrom(value);
      }
      if (unselectedColor_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     */
    public Builder clearUnselectedColor() {
      bitField0_ = (bitField0_ & ~0x00000010);
      unselectedColor_ = null;
      if (unselectedColorBuilder_ != null) {
        unselectedColorBuilder_.dispose();
        unselectedColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPColor.Builder getUnselectedColorBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetUnselectedColorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPColorOrBuilder getUnselectedColorOrBuilder() {
      if (unselectedColorBuilder_ != null) {
        return unselectedColorBuilder_.getMessageOrBuilder();
      } else {
        return unselectedColor_ == null ?
            com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : unselectedColor_;
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder> 
        internalGetUnselectedColorFieldBuilder() {
      if (unselectedColorBuilder_ == null) {
        unselectedColorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder>(
                getUnselectedColor(),
                getParentForChildren(),
                isClean());
        unselectedColor_ = null;
      }
      return unselectedColorBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.renderprotocol.ui.v1.RPBottomNavBar)
  }

  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPBottomNavBar)
  private static final com.nukive.renderprotocol.ui.v1.RPBottomNavBar DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nukive.renderprotocol.ui.v1.RPBottomNavBar();
  }

  public static com.nukive.renderprotocol.ui.v1.RPBottomNavBar getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPBottomNavBar>
      PARSER = new com.google.protobuf.AbstractParser<RPBottomNavBar>() {
    @java.lang.Override
    public RPBottomNavBar parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPBottomNavBar> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPBottomNavBar> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPBottomNavBar getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

