// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

@com.google.protobuf.Generated
public interface RPButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.renderprotocol.ui.v1.RPButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget label = 1 [json_name = "label"];</code>
   * @return Whether the label field is set.
   */
  boolean hasLabel();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget label = 1 [json_name = "label"];</code>
   * @return The label.
   */
  com.nukive.renderprotocol.ui.v1.RPWidget getLabel();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget label = 1 [json_name = "label"];</code>
   */
  com.nukive.renderprotocol.ui.v1.RPWidgetOrBuilder getLabelOrBuilder();

  /**
   * <code>.proto.renderprotocol.ui.v1.RPAction action = 2 [json_name = "action"];</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPAction action = 2 [json_name = "action"];</code>
   * @return The action.
   */
  com.nukive.renderprotocol.ui.v1.RPAction getAction();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPAction action = 2 [json_name = "action"];</code>
   */
  com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getActionOrBuilder();

  /**
   * <code>.proto.renderprotocol.ui.v1.RPButtonStyle style = 3 [json_name = "style"];</code>
   * @return The enum numeric value on the wire for style.
   */
  int getStyleValue();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPButtonStyle style = 3 [json_name = "style"];</code>
   * @return The style.
   */
  com.nukive.renderprotocol.ui.v1.RPButtonStyle getStyle();

  /**
   * <code>bool disabled = 4 [json_name = "disabled"];</code>
   * @return The disabled.
   */
  boolean getDisabled();
}
