// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core_support.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPClipShape")
public inline fun rPClipShape(block: com.nukive.renderprotocol.ui.v1.RPClipShapeKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPClipShape =
  com.nukive.renderprotocol.ui.v1.RPClipShapeKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPClipShape.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPClipShape`
 */
public object RPClipShapeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPClipShape.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPClipShape.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPClipShape = _builder.build()

    /**
     * `.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];`
     */
    public var rectangle: com.nukive.renderprotocol.ui.v1.RPShapeRectangle
      @kotlin.jvm.JvmName("getRectangle")
        get() = _builder.rectangle
      @kotlin.jvm.JvmName("setRectangle")
        set(value) {
        _builder.rectangle = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];`
     */
    public fun clearRectangle() {
      _builder.clearRectangle()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];`
     * @return Whether the rectangle field is set.
     */
    public fun hasRectangle(): kotlin.Boolean {
      return _builder.hasRectangle()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];`
     */
    public var circle: com.nukive.renderprotocol.ui.v1.RPShapeCircle
      @kotlin.jvm.JvmName("getCircle")
        get() = _builder.circle
      @kotlin.jvm.JvmName("setCircle")
        set(value) {
        _builder.circle = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];`
     */
    public fun clearCircle() {
      _builder.clearCircle()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];`
     * @return Whether the circle field is set.
     */
    public fun hasCircle(): kotlin.Boolean {
      return _builder.hasCircle()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];`
     */
    public var ellipse: com.nukive.renderprotocol.ui.v1.RPShapeEllipse
      @kotlin.jvm.JvmName("getEllipse")
        get() = _builder.ellipse
      @kotlin.jvm.JvmName("setEllipse")
        set(value) {
        _builder.ellipse = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];`
     */
    public fun clearEllipse() {
      _builder.clearEllipse()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];`
     * @return Whether the ellipse field is set.
     */
    public fun hasEllipse(): kotlin.Boolean {
      return _builder.hasEllipse()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];`
     */
    public var capsule: com.nukive.renderprotocol.ui.v1.RPShapeCapsule
      @kotlin.jvm.JvmName("getCapsule")
        get() = _builder.capsule
      @kotlin.jvm.JvmName("setCapsule")
        set(value) {
        _builder.capsule = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];`
     */
    public fun clearCapsule() {
      _builder.clearCapsule()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];`
     * @return Whether the capsule field is set.
     */
    public fun hasCapsule(): kotlin.Boolean {
      return _builder.hasCapsule()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];`
     */
    public var roundedRectangle: com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle
      @kotlin.jvm.JvmName("getRoundedRectangle")
        get() = _builder.roundedRectangle
      @kotlin.jvm.JvmName("setRoundedRectangle")
        set(value) {
        _builder.roundedRectangle = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];`
     */
    public fun clearRoundedRectangle() {
      _builder.clearRoundedRectangle()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];`
     * @return Whether the roundedRectangle field is set.
     */
    public fun hasRoundedRectangle(): kotlin.Boolean {
      return _builder.hasRoundedRectangle()
    }
    public val valueCase: com.nukive.renderprotocol.ui.v1.RPClipShape.ValueCase
    @kotlin.jvm.JvmName("getValueCase")
      get() = _builder.getValueCase()

    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPClipShape.copy(block: `com.nukive.renderprotocol.ui.v1`.RPClipShapeKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPClipShape =
  `com.nukive.renderprotocol.ui.v1`.RPClipShapeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPClipShapeOrBuilder.rectangleOrNull: com.nukive.renderprotocol.ui.v1.RPShapeRectangle?
  get() = if (hasRectangle()) getRectangle() else null

public val com.nukive.renderprotocol.ui.v1.RPClipShapeOrBuilder.circleOrNull: com.nukive.renderprotocol.ui.v1.RPShapeCircle?
  get() = if (hasCircle()) getCircle() else null

public val com.nukive.renderprotocol.ui.v1.RPClipShapeOrBuilder.ellipseOrNull: com.nukive.renderprotocol.ui.v1.RPShapeEllipse?
  get() = if (hasEllipse()) getEllipse() else null

public val com.nukive.renderprotocol.ui.v1.RPClipShapeOrBuilder.capsuleOrNull: com.nukive.renderprotocol.ui.v1.RPShapeCapsule?
  get() = if (hasCapsule()) getCapsule() else null

public val com.nukive.renderprotocol.ui.v1.RPClipShapeOrBuilder.roundedRectangleOrNull: com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle?
  get() = if (hasRoundedRectangle()) getRoundedRectangle() else null

