// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core_support.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

/**
 * Protobuf type {@code proto.renderprotocol.ui.v1.RPClipShape}
 */
@com.google.protobuf.Generated
public final class RPClipShape extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.renderprotocol.ui.v1.RPClipShape)
    RPClipShapeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPClipShape");
  }
  // Use RPClipShape.newBuilder() to construct.
  private RPClipShape(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPClipShape() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPClipShape_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPClipShape_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPClipShape_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nukive.renderprotocol.ui.v1.RPClipShape.class, com.nukive.renderprotocol.ui.v1.RPClipShape.Builder.class);
  }

  private int valueCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    RECTANGLE(1),
    CIRCLE(2),
    ELLIPSE(3),
    CAPSULE(4),
    ROUNDED_RECTANGLE(5),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 1: return RECTANGLE;
        case 2: return CIRCLE;
        case 3: return ELLIPSE;
        case 4: return CAPSULE;
        case 5: return ROUNDED_RECTANGLE;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int RECTANGLE_FIELD_NUMBER = 1;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
   * @return Whether the rectangle field is set.
   */
  @java.lang.Override
  public boolean hasRectangle() {
    return valueCase_ == 1;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
   * @return The rectangle.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeRectangle getRectangle() {
    if (valueCase_ == 1) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeRectangle) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeRectangle.getDefaultInstance();
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeRectangleOrBuilder getRectangleOrBuilder() {
    if (valueCase_ == 1) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeRectangle) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeRectangle.getDefaultInstance();
  }

  public static final int CIRCLE_FIELD_NUMBER = 2;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
   * @return Whether the circle field is set.
   */
  @java.lang.Override
  public boolean hasCircle() {
    return valueCase_ == 2;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
   * @return The circle.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeCircle getCircle() {
    if (valueCase_ == 2) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeCircle) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeCircle.getDefaultInstance();
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeCircleOrBuilder getCircleOrBuilder() {
    if (valueCase_ == 2) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeCircle) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeCircle.getDefaultInstance();
  }

  public static final int ELLIPSE_FIELD_NUMBER = 3;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
   * @return Whether the ellipse field is set.
   */
  @java.lang.Override
  public boolean hasEllipse() {
    return valueCase_ == 3;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
   * @return The ellipse.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeEllipse getEllipse() {
    if (valueCase_ == 3) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeEllipse) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeEllipse.getDefaultInstance();
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeEllipseOrBuilder getEllipseOrBuilder() {
    if (valueCase_ == 3) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeEllipse) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeEllipse.getDefaultInstance();
  }

  public static final int CAPSULE_FIELD_NUMBER = 4;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
   * @return Whether the capsule field is set.
   */
  @java.lang.Override
  public boolean hasCapsule() {
    return valueCase_ == 4;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
   * @return The capsule.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeCapsule getCapsule() {
    if (valueCase_ == 4) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeCapsule) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeCapsule.getDefaultInstance();
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeCapsuleOrBuilder getCapsuleOrBuilder() {
    if (valueCase_ == 4) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeCapsule) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeCapsule.getDefaultInstance();
  }

  public static final int ROUNDED_RECTANGLE_FIELD_NUMBER = 5;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
   * @return Whether the roundedRectangle field is set.
   */
  @java.lang.Override
  public boolean hasRoundedRectangle() {
    return valueCase_ == 5;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
   * @return The roundedRectangle.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle getRoundedRectangle() {
    if (valueCase_ == 5) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.getDefaultInstance();
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangleOrBuilder getRoundedRectangleOrBuilder() {
    if (valueCase_ == 5) {
       return (com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle) value_;
    }
    return com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valueCase_ == 1) {
      output.writeMessage(1, (com.nukive.renderprotocol.ui.v1.RPShapeRectangle) value_);
    }
    if (valueCase_ == 2) {
      output.writeMessage(2, (com.nukive.renderprotocol.ui.v1.RPShapeCircle) value_);
    }
    if (valueCase_ == 3) {
      output.writeMessage(3, (com.nukive.renderprotocol.ui.v1.RPShapeEllipse) value_);
    }
    if (valueCase_ == 4) {
      output.writeMessage(4, (com.nukive.renderprotocol.ui.v1.RPShapeCapsule) value_);
    }
    if (valueCase_ == 5) {
      output.writeMessage(5, (com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle) value_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (valueCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.nukive.renderprotocol.ui.v1.RPShapeRectangle) value_);
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.nukive.renderprotocol.ui.v1.RPShapeCircle) value_);
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.nukive.renderprotocol.ui.v1.RPShapeEllipse) value_);
    }
    if (valueCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.nukive.renderprotocol.ui.v1.RPShapeCapsule) value_);
    }
    if (valueCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle) value_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nukive.renderprotocol.ui.v1.RPClipShape)) {
      return super.equals(obj);
    }
    com.nukive.renderprotocol.ui.v1.RPClipShape other = (com.nukive.renderprotocol.ui.v1.RPClipShape) obj;

    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 1:
        if (!getRectangle()
            .equals(other.getRectangle())) return false;
        break;
      case 2:
        if (!getCircle()
            .equals(other.getCircle())) return false;
        break;
      case 3:
        if (!getEllipse()
            .equals(other.getEllipse())) return false;
        break;
      case 4:
        if (!getCapsule()
            .equals(other.getCapsule())) return false;
        break;
      case 5:
        if (!getRoundedRectangle()
            .equals(other.getRoundedRectangle())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (valueCase_) {
      case 1:
        hash = (37 * hash) + RECTANGLE_FIELD_NUMBER;
        hash = (53 * hash) + getRectangle().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CIRCLE_FIELD_NUMBER;
        hash = (53 * hash) + getCircle().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ELLIPSE_FIELD_NUMBER;
        hash = (53 * hash) + getEllipse().hashCode();
        break;
      case 4:
        hash = (37 * hash) + CAPSULE_FIELD_NUMBER;
        hash = (53 * hash) + getCapsule().hashCode();
        break;
      case 5:
        hash = (37 * hash) + ROUNDED_RECTANGLE_FIELD_NUMBER;
        hash = (53 * hash) + getRoundedRectangle().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPClipShape parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nukive.renderprotocol.ui.v1.RPClipShape prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.renderprotocol.ui.v1.RPClipShape}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.renderprotocol.ui.v1.RPClipShape)
      com.nukive.renderprotocol.ui.v1.RPClipShapeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPClipShape_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPClipShape_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nukive.renderprotocol.ui.v1.RPClipShape.class, com.nukive.renderprotocol.ui.v1.RPClipShape.Builder.class);
    }

    // Construct using com.nukive.renderprotocol.ui.v1.RPClipShape.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (rectangleBuilder_ != null) {
        rectangleBuilder_.clear();
      }
      if (circleBuilder_ != null) {
        circleBuilder_.clear();
      }
      if (ellipseBuilder_ != null) {
        ellipseBuilder_.clear();
      }
      if (capsuleBuilder_ != null) {
        capsuleBuilder_.clear();
      }
      if (roundedRectangleBuilder_ != null) {
        roundedRectangleBuilder_.clear();
      }
      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPClipShape_descriptor;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPClipShape getDefaultInstanceForType() {
      return com.nukive.renderprotocol.ui.v1.RPClipShape.getDefaultInstance();
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPClipShape build() {
      com.nukive.renderprotocol.ui.v1.RPClipShape result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPClipShape buildPartial() {
      com.nukive.renderprotocol.ui.v1.RPClipShape result = new com.nukive.renderprotocol.ui.v1.RPClipShape(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nukive.renderprotocol.ui.v1.RPClipShape result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.nukive.renderprotocol.ui.v1.RPClipShape result) {
      result.valueCase_ = valueCase_;
      result.value_ = this.value_;
      if (valueCase_ == 1 &&
          rectangleBuilder_ != null) {
        result.value_ = rectangleBuilder_.build();
      }
      if (valueCase_ == 2 &&
          circleBuilder_ != null) {
        result.value_ = circleBuilder_.build();
      }
      if (valueCase_ == 3 &&
          ellipseBuilder_ != null) {
        result.value_ = ellipseBuilder_.build();
      }
      if (valueCase_ == 4 &&
          capsuleBuilder_ != null) {
        result.value_ = capsuleBuilder_.build();
      }
      if (valueCase_ == 5 &&
          roundedRectangleBuilder_ != null) {
        result.value_ = roundedRectangleBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nukive.renderprotocol.ui.v1.RPClipShape) {
        return mergeFrom((com.nukive.renderprotocol.ui.v1.RPClipShape)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nukive.renderprotocol.ui.v1.RPClipShape other) {
      if (other == com.nukive.renderprotocol.ui.v1.RPClipShape.getDefaultInstance()) return this;
      switch (other.getValueCase()) {
        case RECTANGLE: {
          mergeRectangle(other.getRectangle());
          break;
        }
        case CIRCLE: {
          mergeCircle(other.getCircle());
          break;
        }
        case ELLIPSE: {
          mergeEllipse(other.getEllipse());
          break;
        }
        case CAPSULE: {
          mergeCapsule(other.getCapsule());
          break;
        }
        case ROUNDED_RECTANGLE: {
          mergeRoundedRectangle(other.getRoundedRectangle());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRectangleFieldBuilder().getBuilder(),
                  extensionRegistry);
              valueCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetCircleFieldBuilder().getBuilder(),
                  extensionRegistry);
              valueCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetEllipseFieldBuilder().getBuilder(),
                  extensionRegistry);
              valueCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetCapsuleFieldBuilder().getBuilder(),
                  extensionRegistry);
              valueCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetRoundedRectangleFieldBuilder().getBuilder(),
                  extensionRegistry);
              valueCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeRectangle, com.nukive.renderprotocol.ui.v1.RPShapeRectangle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeRectangleOrBuilder> rectangleBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     * @return Whether the rectangle field is set.
     */
    @java.lang.Override
    public boolean hasRectangle() {
      return valueCase_ == 1;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     * @return The rectangle.
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeRectangle getRectangle() {
      if (rectangleBuilder_ == null) {
        if (valueCase_ == 1) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeRectangle) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeRectangle.getDefaultInstance();
      } else {
        if (valueCase_ == 1) {
          return rectangleBuilder_.getMessage();
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeRectangle.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     */
    public Builder setRectangle(com.nukive.renderprotocol.ui.v1.RPShapeRectangle value) {
      if (rectangleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        rectangleBuilder_.setMessage(value);
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     */
    public Builder setRectangle(
        com.nukive.renderprotocol.ui.v1.RPShapeRectangle.Builder builderForValue) {
      if (rectangleBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        rectangleBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     */
    public Builder mergeRectangle(com.nukive.renderprotocol.ui.v1.RPShapeRectangle value) {
      if (rectangleBuilder_ == null) {
        if (valueCase_ == 1 &&
            value_ != com.nukive.renderprotocol.ui.v1.RPShapeRectangle.getDefaultInstance()) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeRectangle.newBuilder((com.nukive.renderprotocol.ui.v1.RPShapeRectangle) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 1) {
          rectangleBuilder_.mergeFrom(value);
        } else {
          rectangleBuilder_.setMessage(value);
        }
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     */
    public Builder clearRectangle() {
      if (rectangleBuilder_ == null) {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
        }
        rectangleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPShapeRectangle.Builder getRectangleBuilder() {
      return internalGetRectangleFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeRectangleOrBuilder getRectangleOrBuilder() {
      if ((valueCase_ == 1) && (rectangleBuilder_ != null)) {
        return rectangleBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 1) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeRectangle) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeRectangle.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRectangle rectangle = 1 [json_name = "rectangle"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeRectangle, com.nukive.renderprotocol.ui.v1.RPShapeRectangle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeRectangleOrBuilder> 
        internalGetRectangleFieldBuilder() {
      if (rectangleBuilder_ == null) {
        if (!(valueCase_ == 1)) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeRectangle.getDefaultInstance();
        }
        rectangleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPShapeRectangle, com.nukive.renderprotocol.ui.v1.RPShapeRectangle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeRectangleOrBuilder>(
                (com.nukive.renderprotocol.ui.v1.RPShapeRectangle) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 1;
      onChanged();
      return rectangleBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeCircle, com.nukive.renderprotocol.ui.v1.RPShapeCircle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeCircleOrBuilder> circleBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     * @return Whether the circle field is set.
     */
    @java.lang.Override
    public boolean hasCircle() {
      return valueCase_ == 2;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     * @return The circle.
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeCircle getCircle() {
      if (circleBuilder_ == null) {
        if (valueCase_ == 2) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeCircle) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeCircle.getDefaultInstance();
      } else {
        if (valueCase_ == 2) {
          return circleBuilder_.getMessage();
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeCircle.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     */
    public Builder setCircle(com.nukive.renderprotocol.ui.v1.RPShapeCircle value) {
      if (circleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        circleBuilder_.setMessage(value);
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     */
    public Builder setCircle(
        com.nukive.renderprotocol.ui.v1.RPShapeCircle.Builder builderForValue) {
      if (circleBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        circleBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     */
    public Builder mergeCircle(com.nukive.renderprotocol.ui.v1.RPShapeCircle value) {
      if (circleBuilder_ == null) {
        if (valueCase_ == 2 &&
            value_ != com.nukive.renderprotocol.ui.v1.RPShapeCircle.getDefaultInstance()) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeCircle.newBuilder((com.nukive.renderprotocol.ui.v1.RPShapeCircle) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 2) {
          circleBuilder_.mergeFrom(value);
        } else {
          circleBuilder_.setMessage(value);
        }
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     */
    public Builder clearCircle() {
      if (circleBuilder_ == null) {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
        }
        circleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPShapeCircle.Builder getCircleBuilder() {
      return internalGetCircleFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeCircleOrBuilder getCircleOrBuilder() {
      if ((valueCase_ == 2) && (circleBuilder_ != null)) {
        return circleBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 2) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeCircle) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeCircle.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCircle circle = 2 [json_name = "circle"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeCircle, com.nukive.renderprotocol.ui.v1.RPShapeCircle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeCircleOrBuilder> 
        internalGetCircleFieldBuilder() {
      if (circleBuilder_ == null) {
        if (!(valueCase_ == 2)) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeCircle.getDefaultInstance();
        }
        circleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPShapeCircle, com.nukive.renderprotocol.ui.v1.RPShapeCircle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeCircleOrBuilder>(
                (com.nukive.renderprotocol.ui.v1.RPShapeCircle) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 2;
      onChanged();
      return circleBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeEllipse, com.nukive.renderprotocol.ui.v1.RPShapeEllipse.Builder, com.nukive.renderprotocol.ui.v1.RPShapeEllipseOrBuilder> ellipseBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     * @return Whether the ellipse field is set.
     */
    @java.lang.Override
    public boolean hasEllipse() {
      return valueCase_ == 3;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     * @return The ellipse.
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeEllipse getEllipse() {
      if (ellipseBuilder_ == null) {
        if (valueCase_ == 3) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeEllipse) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeEllipse.getDefaultInstance();
      } else {
        if (valueCase_ == 3) {
          return ellipseBuilder_.getMessage();
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeEllipse.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     */
    public Builder setEllipse(com.nukive.renderprotocol.ui.v1.RPShapeEllipse value) {
      if (ellipseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        ellipseBuilder_.setMessage(value);
      }
      valueCase_ = 3;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     */
    public Builder setEllipse(
        com.nukive.renderprotocol.ui.v1.RPShapeEllipse.Builder builderForValue) {
      if (ellipseBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        ellipseBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 3;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     */
    public Builder mergeEllipse(com.nukive.renderprotocol.ui.v1.RPShapeEllipse value) {
      if (ellipseBuilder_ == null) {
        if (valueCase_ == 3 &&
            value_ != com.nukive.renderprotocol.ui.v1.RPShapeEllipse.getDefaultInstance()) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeEllipse.newBuilder((com.nukive.renderprotocol.ui.v1.RPShapeEllipse) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 3) {
          ellipseBuilder_.mergeFrom(value);
        } else {
          ellipseBuilder_.setMessage(value);
        }
      }
      valueCase_ = 3;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     */
    public Builder clearEllipse() {
      if (ellipseBuilder_ == null) {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
        }
        ellipseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPShapeEllipse.Builder getEllipseBuilder() {
      return internalGetEllipseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeEllipseOrBuilder getEllipseOrBuilder() {
      if ((valueCase_ == 3) && (ellipseBuilder_ != null)) {
        return ellipseBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 3) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeEllipse) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeEllipse.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeEllipse ellipse = 3 [json_name = "ellipse"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeEllipse, com.nukive.renderprotocol.ui.v1.RPShapeEllipse.Builder, com.nukive.renderprotocol.ui.v1.RPShapeEllipseOrBuilder> 
        internalGetEllipseFieldBuilder() {
      if (ellipseBuilder_ == null) {
        if (!(valueCase_ == 3)) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeEllipse.getDefaultInstance();
        }
        ellipseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPShapeEllipse, com.nukive.renderprotocol.ui.v1.RPShapeEllipse.Builder, com.nukive.renderprotocol.ui.v1.RPShapeEllipseOrBuilder>(
                (com.nukive.renderprotocol.ui.v1.RPShapeEllipse) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 3;
      onChanged();
      return ellipseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeCapsule, com.nukive.renderprotocol.ui.v1.RPShapeCapsule.Builder, com.nukive.renderprotocol.ui.v1.RPShapeCapsuleOrBuilder> capsuleBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     * @return Whether the capsule field is set.
     */
    @java.lang.Override
    public boolean hasCapsule() {
      return valueCase_ == 4;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     * @return The capsule.
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeCapsule getCapsule() {
      if (capsuleBuilder_ == null) {
        if (valueCase_ == 4) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeCapsule) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeCapsule.getDefaultInstance();
      } else {
        if (valueCase_ == 4) {
          return capsuleBuilder_.getMessage();
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeCapsule.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     */
    public Builder setCapsule(com.nukive.renderprotocol.ui.v1.RPShapeCapsule value) {
      if (capsuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        capsuleBuilder_.setMessage(value);
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     */
    public Builder setCapsule(
        com.nukive.renderprotocol.ui.v1.RPShapeCapsule.Builder builderForValue) {
      if (capsuleBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        capsuleBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     */
    public Builder mergeCapsule(com.nukive.renderprotocol.ui.v1.RPShapeCapsule value) {
      if (capsuleBuilder_ == null) {
        if (valueCase_ == 4 &&
            value_ != com.nukive.renderprotocol.ui.v1.RPShapeCapsule.getDefaultInstance()) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeCapsule.newBuilder((com.nukive.renderprotocol.ui.v1.RPShapeCapsule) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 4) {
          capsuleBuilder_.mergeFrom(value);
        } else {
          capsuleBuilder_.setMessage(value);
        }
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     */
    public Builder clearCapsule() {
      if (capsuleBuilder_ == null) {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
        }
        capsuleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPShapeCapsule.Builder getCapsuleBuilder() {
      return internalGetCapsuleFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeCapsuleOrBuilder getCapsuleOrBuilder() {
      if ((valueCase_ == 4) && (capsuleBuilder_ != null)) {
        return capsuleBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 4) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeCapsule) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeCapsule.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeCapsule capsule = 4 [json_name = "capsule"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeCapsule, com.nukive.renderprotocol.ui.v1.RPShapeCapsule.Builder, com.nukive.renderprotocol.ui.v1.RPShapeCapsuleOrBuilder> 
        internalGetCapsuleFieldBuilder() {
      if (capsuleBuilder_ == null) {
        if (!(valueCase_ == 4)) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeCapsule.getDefaultInstance();
        }
        capsuleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPShapeCapsule, com.nukive.renderprotocol.ui.v1.RPShapeCapsule.Builder, com.nukive.renderprotocol.ui.v1.RPShapeCapsuleOrBuilder>(
                (com.nukive.renderprotocol.ui.v1.RPShapeCapsule) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 4;
      onChanged();
      return capsuleBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle, com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangleOrBuilder> roundedRectangleBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     * @return Whether the roundedRectangle field is set.
     */
    @java.lang.Override
    public boolean hasRoundedRectangle() {
      return valueCase_ == 5;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     * @return The roundedRectangle.
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle getRoundedRectangle() {
      if (roundedRectangleBuilder_ == null) {
        if (valueCase_ == 5) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.getDefaultInstance();
      } else {
        if (valueCase_ == 5) {
          return roundedRectangleBuilder_.getMessage();
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     */
    public Builder setRoundedRectangle(com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle value) {
      if (roundedRectangleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        roundedRectangleBuilder_.setMessage(value);
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     */
    public Builder setRoundedRectangle(
        com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.Builder builderForValue) {
      if (roundedRectangleBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        roundedRectangleBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     */
    public Builder mergeRoundedRectangle(com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle value) {
      if (roundedRectangleBuilder_ == null) {
        if (valueCase_ == 5 &&
            value_ != com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.getDefaultInstance()) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.newBuilder((com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 5) {
          roundedRectangleBuilder_.mergeFrom(value);
        } else {
          roundedRectangleBuilder_.setMessage(value);
        }
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     */
    public Builder clearRoundedRectangle() {
      if (roundedRectangleBuilder_ == null) {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
        }
        roundedRectangleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.Builder getRoundedRectangleBuilder() {
      return internalGetRoundedRectangleFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     */
    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangleOrBuilder getRoundedRectangleOrBuilder() {
      if ((valueCase_ == 5) && (roundedRectangleBuilder_ != null)) {
        return roundedRectangleBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 5) {
          return (com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle) value_;
        }
        return com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.getDefaultInstance();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPShapeRoundedRectangle rounded_rectangle = 5 [json_name = "roundedRectangle"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle, com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangleOrBuilder> 
        internalGetRoundedRectangleFieldBuilder() {
      if (roundedRectangleBuilder_ == null) {
        if (!(valueCase_ == 5)) {
          value_ = com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.getDefaultInstance();
        }
        roundedRectangleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle, com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle.Builder, com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangleOrBuilder>(
                (com.nukive.renderprotocol.ui.v1.RPShapeRoundedRectangle) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 5;
      onChanged();
      return roundedRectangleBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.renderprotocol.ui.v1.RPClipShape)
  }

  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPClipShape)
  private static final com.nukive.renderprotocol.ui.v1.RPClipShape DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nukive.renderprotocol.ui.v1.RPClipShape();
  }

  public static com.nukive.renderprotocol.ui.v1.RPClipShape getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPClipShape>
      PARSER = new com.google.protobuf.AbstractParser<RPClipShape>() {
    @java.lang.Override
    public RPClipShape parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPClipShape> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPClipShape> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPClipShape getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

