// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_image.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

/**
 * Protobuf enum {@code proto.renderprotocol.ui.v1.RPContentMode}
 */
@com.google.protobuf.Generated
public enum RPContentMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RP_CONTENT_MODE_UNSPECIFIED = 0;</code>
   */
  RP_CONTENT_MODE_UNSPECIFIED(0),
  /**
   * <code>RP_CONTENT_MODE_FIT = 1;</code>
   */
  RP_CONTENT_MODE_FIT(1),
  /**
   * <code>RP_CONTENT_MODE_FILL = 2;</code>
   */
  RP_CONTENT_MODE_FILL(2),
  /**
   * <code>RP_CONTENT_MODE_STRETCH = 3;</code>
   */
  RP_CONTENT_MODE_STRETCH(3),
  /**
   * <code>RP_CONTENT_MODE_NONE = 4;</code>
   */
  RP_CONTENT_MODE_NONE(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPContentMode");
  }
  /**
   * <code>RP_CONTENT_MODE_UNSPECIFIED = 0;</code>
   */
  public static final int RP_CONTENT_MODE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>RP_CONTENT_MODE_FIT = 1;</code>
   */
  public static final int RP_CONTENT_MODE_FIT_VALUE = 1;
  /**
   * <code>RP_CONTENT_MODE_FILL = 2;</code>
   */
  public static final int RP_CONTENT_MODE_FILL_VALUE = 2;
  /**
   * <code>RP_CONTENT_MODE_STRETCH = 3;</code>
   */
  public static final int RP_CONTENT_MODE_STRETCH_VALUE = 3;
  /**
   * <code>RP_CONTENT_MODE_NONE = 4;</code>
   */
  public static final int RP_CONTENT_MODE_NONE_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RPContentMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RPContentMode forNumber(int value) {
    switch (value) {
      case 0: return RP_CONTENT_MODE_UNSPECIFIED;
      case 1: return RP_CONTENT_MODE_FIT;
      case 2: return RP_CONTENT_MODE_FILL;
      case 3: return RP_CONTENT_MODE_STRETCH;
      case 4: return RP_CONTENT_MODE_NONE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RPContentMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RPContentMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RPContentMode>() {
          public RPContentMode findValueByNumber(int number) {
            return RPContentMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.nukive.renderprotocol.ui.v1.RpUiImageProto.getDescriptor().getEnumType(0);
  }

  private static final RPContentMode[] VALUES = values();

  public static RPContentMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RPContentMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.renderprotocol.ui.v1.RPContentMode)
}

