// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_color.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPColorValue")
public inline fun rPColorValue(block: com.nukive.renderprotocol.ui.v1.RPColorValueKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPColorValue =
  com.nukive.renderprotocol.ui.v1.RPColorValueKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPColorValue.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPColorValue`
 */
public object RPColorValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPColorValue.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPColorValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPColorValue = _builder.build()

    /**
     * `.proto.renderprotocol.ui.v1.RPColor solid = 1 [json_name = "solid"];`
     */
    public var solid: com.nukive.renderprotocol.ui.v1.RPColor
      @kotlin.jvm.JvmName("getSolid")
        get() = _builder.solid
      @kotlin.jvm.JvmName("setSolid")
        set(value) {
        _builder.solid = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPColor solid = 1 [json_name = "solid"];`
     */
    public fun clearSolid() {
      _builder.clearSolid()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPColor solid = 1 [json_name = "solid"];`
     * @return Whether the solid field is set.
     */
    public fun hasSolid(): kotlin.Boolean {
      return _builder.hasSolid()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPLinearGradient linear_gradient = 2 [json_name = "linearGradient"];`
     */
    public var linearGradient: com.nukive.renderprotocol.ui.v1.RPLinearGradient
      @kotlin.jvm.JvmName("getLinearGradient")
        get() = _builder.linearGradient
      @kotlin.jvm.JvmName("setLinearGradient")
        set(value) {
        _builder.linearGradient = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPLinearGradient linear_gradient = 2 [json_name = "linearGradient"];`
     */
    public fun clearLinearGradient() {
      _builder.clearLinearGradient()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPLinearGradient linear_gradient = 2 [json_name = "linearGradient"];`
     * @return Whether the linearGradient field is set.
     */
    public fun hasLinearGradient(): kotlin.Boolean {
      return _builder.hasLinearGradient()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPRadialGradient radial_gradient = 3 [json_name = "radialGradient"];`
     */
    public var radialGradient: com.nukive.renderprotocol.ui.v1.RPRadialGradient
      @kotlin.jvm.JvmName("getRadialGradient")
        get() = _builder.radialGradient
      @kotlin.jvm.JvmName("setRadialGradient")
        set(value) {
        _builder.radialGradient = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPRadialGradient radial_gradient = 3 [json_name = "radialGradient"];`
     */
    public fun clearRadialGradient() {
      _builder.clearRadialGradient()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPRadialGradient radial_gradient = 3 [json_name = "radialGradient"];`
     * @return Whether the radialGradient field is set.
     */
    public fun hasRadialGradient(): kotlin.Boolean {
      return _builder.hasRadialGradient()
    }
    public val valueCase: com.nukive.renderprotocol.ui.v1.RPColorValue.ValueCase
    @kotlin.jvm.JvmName("getValueCase")
      get() = _builder.getValueCase()

    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPColorValue.copy(block: `com.nukive.renderprotocol.ui.v1`.RPColorValueKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPColorValue =
  `com.nukive.renderprotocol.ui.v1`.RPColorValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPColorValueOrBuilder.solidOrNull: com.nukive.renderprotocol.ui.v1.RPColor?
  get() = if (hasSolid()) getSolid() else null

public val com.nukive.renderprotocol.ui.v1.RPColorValueOrBuilder.linearGradientOrNull: com.nukive.renderprotocol.ui.v1.RPLinearGradient?
  get() = if (hasLinearGradient()) getLinearGradient() else null

public val com.nukive.renderprotocol.ui.v1.RPColorValueOrBuilder.radialGradientOrNull: com.nukive.renderprotocol.ui.v1.RPRadialGradient?
  get() = if (hasRadialGradient()) getRadialGradient() else null

