// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

@com.google.protobuf.Generated
public interface RPExpandedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.renderprotocol.ui.v1.RPExpanded)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
   * @return Whether the child field is set.
   */
  boolean hasChild();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
   * @return The child.
   */
  com.nukive.renderprotocol.ui.v1.RPWidget getChild();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
   */
  com.nukive.renderprotocol.ui.v1.RPWidgetOrBuilder getChildOrBuilder();

  /**
   * <code>int32 flex = 2 [json_name = "flex"];</code>
   * @return The flex.
   */
  int getFlex();
}
