// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core_support.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

/**
 * Protobuf type {@code proto.renderprotocol.ui.v1.RPExplicitPadding}
 */
@com.google.protobuf.Generated
public final class RPExplicitPadding extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.renderprotocol.ui.v1.RPExplicitPadding)
    RPExplicitPaddingOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPExplicitPadding");
  }
  // Use RPExplicitPadding.newBuilder() to construct.
  private RPExplicitPadding(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPExplicitPadding() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPExplicitPadding_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPExplicitPadding_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPExplicitPadding_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nukive.renderprotocol.ui.v1.RPExplicitPadding.class, com.nukive.renderprotocol.ui.v1.RPExplicitPadding.Builder.class);
  }

  public static final int TOP_FIELD_NUMBER = 1;
  private float top_ = 0F;
  /**
   * <code>float top = 1 [json_name = "top"];</code>
   * @return The top.
   */
  @java.lang.Override
  public float getTop() {
    return top_;
  }

  public static final int BOTTOM_FIELD_NUMBER = 2;
  private float bottom_ = 0F;
  /**
   * <code>float bottom = 2 [json_name = "bottom"];</code>
   * @return The bottom.
   */
  @java.lang.Override
  public float getBottom() {
    return bottom_;
  }

  public static final int LEFT_FIELD_NUMBER = 3;
  private float left_ = 0F;
  /**
   * <code>float left = 3 [json_name = "left"];</code>
   * @return The left.
   */
  @java.lang.Override
  public float getLeft() {
    return left_;
  }

  public static final int RIGHT_FIELD_NUMBER = 4;
  private float right_ = 0F;
  /**
   * <code>float right = 4 [json_name = "right"];</code>
   * @return The right.
   */
  @java.lang.Override
  public float getRight() {
    return right_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(top_) != 0) {
      output.writeFloat(1, top_);
    }
    if (java.lang.Float.floatToRawIntBits(bottom_) != 0) {
      output.writeFloat(2, bottom_);
    }
    if (java.lang.Float.floatToRawIntBits(left_) != 0) {
      output.writeFloat(3, left_);
    }
    if (java.lang.Float.floatToRawIntBits(right_) != 0) {
      output.writeFloat(4, right_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (java.lang.Float.floatToRawIntBits(top_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, top_);
    }
    if (java.lang.Float.floatToRawIntBits(bottom_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, bottom_);
    }
    if (java.lang.Float.floatToRawIntBits(left_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, left_);
    }
    if (java.lang.Float.floatToRawIntBits(right_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, right_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nukive.renderprotocol.ui.v1.RPExplicitPadding)) {
      return super.equals(obj);
    }
    com.nukive.renderprotocol.ui.v1.RPExplicitPadding other = (com.nukive.renderprotocol.ui.v1.RPExplicitPadding) obj;

    if (java.lang.Float.floatToIntBits(getTop())
        != java.lang.Float.floatToIntBits(
            other.getTop())) return false;
    if (java.lang.Float.floatToIntBits(getBottom())
        != java.lang.Float.floatToIntBits(
            other.getBottom())) return false;
    if (java.lang.Float.floatToIntBits(getLeft())
        != java.lang.Float.floatToIntBits(
            other.getLeft())) return false;
    if (java.lang.Float.floatToIntBits(getRight())
        != java.lang.Float.floatToIntBits(
            other.getRight())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOP_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTop());
    hash = (37 * hash) + BOTTOM_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBottom());
    hash = (37 * hash) + LEFT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLeft());
    hash = (37 * hash) + RIGHT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRight());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nukive.renderprotocol.ui.v1.RPExplicitPadding prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.renderprotocol.ui.v1.RPExplicitPadding}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.renderprotocol.ui.v1.RPExplicitPadding)
      com.nukive.renderprotocol.ui.v1.RPExplicitPaddingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPExplicitPadding_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPExplicitPadding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nukive.renderprotocol.ui.v1.RPExplicitPadding.class, com.nukive.renderprotocol.ui.v1.RPExplicitPadding.Builder.class);
    }

    // Construct using com.nukive.renderprotocol.ui.v1.RPExplicitPadding.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      top_ = 0F;
      bottom_ = 0F;
      left_ = 0F;
      right_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.internal_static_proto_renderprotocol_ui_v1_RPExplicitPadding_descriptor;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPExplicitPadding getDefaultInstanceForType() {
      return com.nukive.renderprotocol.ui.v1.RPExplicitPadding.getDefaultInstance();
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPExplicitPadding build() {
      com.nukive.renderprotocol.ui.v1.RPExplicitPadding result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPExplicitPadding buildPartial() {
      com.nukive.renderprotocol.ui.v1.RPExplicitPadding result = new com.nukive.renderprotocol.ui.v1.RPExplicitPadding(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nukive.renderprotocol.ui.v1.RPExplicitPadding result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.top_ = top_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bottom_ = bottom_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.left_ = left_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.right_ = right_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nukive.renderprotocol.ui.v1.RPExplicitPadding) {
        return mergeFrom((com.nukive.renderprotocol.ui.v1.RPExplicitPadding)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nukive.renderprotocol.ui.v1.RPExplicitPadding other) {
      if (other == com.nukive.renderprotocol.ui.v1.RPExplicitPadding.getDefaultInstance()) return this;
      if (java.lang.Float.floatToRawIntBits(other.getTop()) != 0) {
        setTop(other.getTop());
      }
      if (java.lang.Float.floatToRawIntBits(other.getBottom()) != 0) {
        setBottom(other.getBottom());
      }
      if (java.lang.Float.floatToRawIntBits(other.getLeft()) != 0) {
        setLeft(other.getLeft());
      }
      if (java.lang.Float.floatToRawIntBits(other.getRight()) != 0) {
        setRight(other.getRight());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              top_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              bottom_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              left_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              right_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float top_ ;
    /**
     * <code>float top = 1 [json_name = "top"];</code>
     * @return The top.
     */
    @java.lang.Override
    public float getTop() {
      return top_;
    }
    /**
     * <code>float top = 1 [json_name = "top"];</code>
     * @param value The top to set.
     * @return This builder for chaining.
     */
    public Builder setTop(float value) {

      top_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float top = 1 [json_name = "top"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTop() {
      bitField0_ = (bitField0_ & ~0x00000001);
      top_ = 0F;
      onChanged();
      return this;
    }

    private float bottom_ ;
    /**
     * <code>float bottom = 2 [json_name = "bottom"];</code>
     * @return The bottom.
     */
    @java.lang.Override
    public float getBottom() {
      return bottom_;
    }
    /**
     * <code>float bottom = 2 [json_name = "bottom"];</code>
     * @param value The bottom to set.
     * @return This builder for chaining.
     */
    public Builder setBottom(float value) {

      bottom_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float bottom = 2 [json_name = "bottom"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBottom() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bottom_ = 0F;
      onChanged();
      return this;
    }

    private float left_ ;
    /**
     * <code>float left = 3 [json_name = "left"];</code>
     * @return The left.
     */
    @java.lang.Override
    public float getLeft() {
      return left_;
    }
    /**
     * <code>float left = 3 [json_name = "left"];</code>
     * @param value The left to set.
     * @return This builder for chaining.
     */
    public Builder setLeft(float value) {

      left_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float left = 3 [json_name = "left"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLeft() {
      bitField0_ = (bitField0_ & ~0x00000004);
      left_ = 0F;
      onChanged();
      return this;
    }

    private float right_ ;
    /**
     * <code>float right = 4 [json_name = "right"];</code>
     * @return The right.
     */
    @java.lang.Override
    public float getRight() {
      return right_;
    }
    /**
     * <code>float right = 4 [json_name = "right"];</code>
     * @param value The right to set.
     * @return This builder for chaining.
     */
    public Builder setRight(float value) {

      right_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float right = 4 [json_name = "right"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRight() {
      bitField0_ = (bitField0_ & ~0x00000008);
      right_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.renderprotocol.ui.v1.RPExplicitPadding)
  }

  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPExplicitPadding)
  private static final com.nukive.renderprotocol.ui.v1.RPExplicitPadding DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nukive.renderprotocol.ui.v1.RPExplicitPadding();
  }

  public static com.nukive.renderprotocol.ui.v1.RPExplicitPadding getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPExplicitPadding>
      PARSER = new com.google.protobuf.AbstractParser<RPExplicitPadding>() {
    @java.lang.Override
    public RPExplicitPadding parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPExplicitPadding> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPExplicitPadding> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPExplicitPadding getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

