// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

/**
 * Protobuf type {@code proto.renderprotocol.ui.v1.RPGestureDetector}
 */
@com.google.protobuf.Generated
public final class RPGestureDetector extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.renderprotocol.ui.v1.RPGestureDetector)
    RPGestureDetectorOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPGestureDetector");
  }
  // Use RPGestureDetector.newBuilder() to construct.
  private RPGestureDetector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPGestureDetector() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreProto.internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreProto.internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nukive.renderprotocol.ui.v1.RpUiCoreProto.internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nukive.renderprotocol.ui.v1.RPGestureDetector.class, com.nukive.renderprotocol.ui.v1.RPGestureDetector.Builder.class);
  }

  private int bitField0_;
  public static final int CHILD_FIELD_NUMBER = 1;
  private com.nukive.renderprotocol.ui.v1.RPWidget child_;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
   * @return Whether the child field is set.
   */
  @java.lang.Override
  public boolean hasChild() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
   * @return The child.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPWidget getChild() {
    return child_ == null ? com.nukive.renderprotocol.ui.v1.RPWidget.getDefaultInstance() : child_;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPWidgetOrBuilder getChildOrBuilder() {
    return child_ == null ? com.nukive.renderprotocol.ui.v1.RPWidget.getDefaultInstance() : child_;
  }

  public static final int ON_TAP_FIELD_NUMBER = 2;
  private com.nukive.renderprotocol.ui.v1.RPAction onTap_;
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
   * @return Whether the onTap field is set.
   */
  @java.lang.Override
  public boolean hasOnTap() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
   * @return The onTap.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPAction getOnTap() {
    return onTap_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onTap_;
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getOnTapOrBuilder() {
    return onTap_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onTap_;
  }

  public static final int ON_LONG_PRESS_FIELD_NUMBER = 3;
  private com.nukive.renderprotocol.ui.v1.RPAction onLongPress_;
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
   * @return Whether the onLongPress field is set.
   */
  @java.lang.Override
  public boolean hasOnLongPress() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
   * @return The onLongPress.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPAction getOnLongPress() {
    return onLongPress_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onLongPress_;
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getOnLongPressOrBuilder() {
    return onLongPress_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onLongPress_;
  }

  public static final int ON_DOUBLE_TAP_FIELD_NUMBER = 4;
  private com.nukive.renderprotocol.ui.v1.RPAction onDoubleTap_;
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
   * @return Whether the onDoubleTap field is set.
   */
  @java.lang.Override
  public boolean hasOnDoubleTap() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
   * @return The onDoubleTap.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPAction getOnDoubleTap() {
    return onDoubleTap_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onDoubleTap_;
  }
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getOnDoubleTapOrBuilder() {
    return onDoubleTap_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onDoubleTap_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getChild());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getOnTap());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getOnLongPress());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getOnDoubleTap());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChild());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOnTap());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getOnLongPress());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOnDoubleTap());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nukive.renderprotocol.ui.v1.RPGestureDetector)) {
      return super.equals(obj);
    }
    com.nukive.renderprotocol.ui.v1.RPGestureDetector other = (com.nukive.renderprotocol.ui.v1.RPGestureDetector) obj;

    if (hasChild() != other.hasChild()) return false;
    if (hasChild()) {
      if (!getChild()
          .equals(other.getChild())) return false;
    }
    if (hasOnTap() != other.hasOnTap()) return false;
    if (hasOnTap()) {
      if (!getOnTap()
          .equals(other.getOnTap())) return false;
    }
    if (hasOnLongPress() != other.hasOnLongPress()) return false;
    if (hasOnLongPress()) {
      if (!getOnLongPress()
          .equals(other.getOnLongPress())) return false;
    }
    if (hasOnDoubleTap() != other.hasOnDoubleTap()) return false;
    if (hasOnDoubleTap()) {
      if (!getOnDoubleTap()
          .equals(other.getOnDoubleTap())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChild()) {
      hash = (37 * hash) + CHILD_FIELD_NUMBER;
      hash = (53 * hash) + getChild().hashCode();
    }
    if (hasOnTap()) {
      hash = (37 * hash) + ON_TAP_FIELD_NUMBER;
      hash = (53 * hash) + getOnTap().hashCode();
    }
    if (hasOnLongPress()) {
      hash = (37 * hash) + ON_LONG_PRESS_FIELD_NUMBER;
      hash = (53 * hash) + getOnLongPress().hashCode();
    }
    if (hasOnDoubleTap()) {
      hash = (37 * hash) + ON_DOUBLE_TAP_FIELD_NUMBER;
      hash = (53 * hash) + getOnDoubleTap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nukive.renderprotocol.ui.v1.RPGestureDetector prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.renderprotocol.ui.v1.RPGestureDetector}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.renderprotocol.ui.v1.RPGestureDetector)
      com.nukive.renderprotocol.ui.v1.RPGestureDetectorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreProto.internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreProto.internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nukive.renderprotocol.ui.v1.RPGestureDetector.class, com.nukive.renderprotocol.ui.v1.RPGestureDetector.Builder.class);
    }

    // Construct using com.nukive.renderprotocol.ui.v1.RPGestureDetector.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetChildFieldBuilder();
        internalGetOnTapFieldBuilder();
        internalGetOnLongPressFieldBuilder();
        internalGetOnDoubleTapFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      child_ = null;
      if (childBuilder_ != null) {
        childBuilder_.dispose();
        childBuilder_ = null;
      }
      onTap_ = null;
      if (onTapBuilder_ != null) {
        onTapBuilder_.dispose();
        onTapBuilder_ = null;
      }
      onLongPress_ = null;
      if (onLongPressBuilder_ != null) {
        onLongPressBuilder_.dispose();
        onLongPressBuilder_ = null;
      }
      onDoubleTap_ = null;
      if (onDoubleTapBuilder_ != null) {
        onDoubleTapBuilder_.dispose();
        onDoubleTapBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nukive.renderprotocol.ui.v1.RpUiCoreProto.internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_descriptor;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPGestureDetector getDefaultInstanceForType() {
      return com.nukive.renderprotocol.ui.v1.RPGestureDetector.getDefaultInstance();
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPGestureDetector build() {
      com.nukive.renderprotocol.ui.v1.RPGestureDetector result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPGestureDetector buildPartial() {
      com.nukive.renderprotocol.ui.v1.RPGestureDetector result = new com.nukive.renderprotocol.ui.v1.RPGestureDetector(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nukive.renderprotocol.ui.v1.RPGestureDetector result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.child_ = childBuilder_ == null
            ? child_
            : childBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.onTap_ = onTapBuilder_ == null
            ? onTap_
            : onTapBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.onLongPress_ = onLongPressBuilder_ == null
            ? onLongPress_
            : onLongPressBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.onDoubleTap_ = onDoubleTapBuilder_ == null
            ? onDoubleTap_
            : onDoubleTapBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nukive.renderprotocol.ui.v1.RPGestureDetector) {
        return mergeFrom((com.nukive.renderprotocol.ui.v1.RPGestureDetector)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nukive.renderprotocol.ui.v1.RPGestureDetector other) {
      if (other == com.nukive.renderprotocol.ui.v1.RPGestureDetector.getDefaultInstance()) return this;
      if (other.hasChild()) {
        mergeChild(other.getChild());
      }
      if (other.hasOnTap()) {
        mergeOnTap(other.getOnTap());
      }
      if (other.hasOnLongPress()) {
        mergeOnLongPress(other.getOnLongPress());
      }
      if (other.hasOnDoubleTap()) {
        mergeOnDoubleTap(other.getOnDoubleTap());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetChildFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetOnTapFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetOnLongPressFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetOnDoubleTapFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.nukive.renderprotocol.ui.v1.RPWidget child_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPWidget, com.nukive.renderprotocol.ui.v1.RPWidget.Builder, com.nukive.renderprotocol.ui.v1.RPWidgetOrBuilder> childBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     * @return Whether the child field is set.
     */
    public boolean hasChild() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     * @return The child.
     */
    public com.nukive.renderprotocol.ui.v1.RPWidget getChild() {
      if (childBuilder_ == null) {
        return child_ == null ? com.nukive.renderprotocol.ui.v1.RPWidget.getDefaultInstance() : child_;
      } else {
        return childBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     */
    public Builder setChild(com.nukive.renderprotocol.ui.v1.RPWidget value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        child_ = value;
      } else {
        childBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     */
    public Builder setChild(
        com.nukive.renderprotocol.ui.v1.RPWidget.Builder builderForValue) {
      if (childBuilder_ == null) {
        child_ = builderForValue.build();
      } else {
        childBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     */
    public Builder mergeChild(com.nukive.renderprotocol.ui.v1.RPWidget value) {
      if (childBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          child_ != null &&
          child_ != com.nukive.renderprotocol.ui.v1.RPWidget.getDefaultInstance()) {
          getChildBuilder().mergeFrom(value);
        } else {
          child_ = value;
        }
      } else {
        childBuilder_.mergeFrom(value);
      }
      if (child_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     */
    public Builder clearChild() {
      bitField0_ = (bitField0_ & ~0x00000001);
      child_ = null;
      if (childBuilder_ != null) {
        childBuilder_.dispose();
        childBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPWidget.Builder getChildBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetChildFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPWidgetOrBuilder getChildOrBuilder() {
      if (childBuilder_ != null) {
        return childBuilder_.getMessageOrBuilder();
      } else {
        return child_ == null ?
            com.nukive.renderprotocol.ui.v1.RPWidget.getDefaultInstance() : child_;
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPWidget, com.nukive.renderprotocol.ui.v1.RPWidget.Builder, com.nukive.renderprotocol.ui.v1.RPWidgetOrBuilder> 
        internalGetChildFieldBuilder() {
      if (childBuilder_ == null) {
        childBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPWidget, com.nukive.renderprotocol.ui.v1.RPWidget.Builder, com.nukive.renderprotocol.ui.v1.RPWidgetOrBuilder>(
                getChild(),
                getParentForChildren(),
                isClean());
        child_ = null;
      }
      return childBuilder_;
    }

    private com.nukive.renderprotocol.ui.v1.RPAction onTap_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder> onTapBuilder_;
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     * @return Whether the onTap field is set.
     */
    public boolean hasOnTap() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     * @return The onTap.
     */
    public com.nukive.renderprotocol.ui.v1.RPAction getOnTap() {
      if (onTapBuilder_ == null) {
        return onTap_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onTap_;
      } else {
        return onTapBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     */
    public Builder setOnTap(com.nukive.renderprotocol.ui.v1.RPAction value) {
      if (onTapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        onTap_ = value;
      } else {
        onTapBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     */
    public Builder setOnTap(
        com.nukive.renderprotocol.ui.v1.RPAction.Builder builderForValue) {
      if (onTapBuilder_ == null) {
        onTap_ = builderForValue.build();
      } else {
        onTapBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     */
    public Builder mergeOnTap(com.nukive.renderprotocol.ui.v1.RPAction value) {
      if (onTapBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          onTap_ != null &&
          onTap_ != com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance()) {
          getOnTapBuilder().mergeFrom(value);
        } else {
          onTap_ = value;
        }
      } else {
        onTapBuilder_.mergeFrom(value);
      }
      if (onTap_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     */
    public Builder clearOnTap() {
      bitField0_ = (bitField0_ & ~0x00000002);
      onTap_ = null;
      if (onTapBuilder_ != null) {
        onTapBuilder_.dispose();
        onTapBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPAction.Builder getOnTapBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetOnTapFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getOnTapOrBuilder() {
      if (onTapBuilder_ != null) {
        return onTapBuilder_.getMessageOrBuilder();
      } else {
        return onTap_ == null ?
            com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onTap_;
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_tap = 2 [json_name = "onTap"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder> 
        internalGetOnTapFieldBuilder() {
      if (onTapBuilder_ == null) {
        onTapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder>(
                getOnTap(),
                getParentForChildren(),
                isClean());
        onTap_ = null;
      }
      return onTapBuilder_;
    }

    private com.nukive.renderprotocol.ui.v1.RPAction onLongPress_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder> onLongPressBuilder_;
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     * @return Whether the onLongPress field is set.
     */
    public boolean hasOnLongPress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     * @return The onLongPress.
     */
    public com.nukive.renderprotocol.ui.v1.RPAction getOnLongPress() {
      if (onLongPressBuilder_ == null) {
        return onLongPress_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onLongPress_;
      } else {
        return onLongPressBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     */
    public Builder setOnLongPress(com.nukive.renderprotocol.ui.v1.RPAction value) {
      if (onLongPressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        onLongPress_ = value;
      } else {
        onLongPressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     */
    public Builder setOnLongPress(
        com.nukive.renderprotocol.ui.v1.RPAction.Builder builderForValue) {
      if (onLongPressBuilder_ == null) {
        onLongPress_ = builderForValue.build();
      } else {
        onLongPressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     */
    public Builder mergeOnLongPress(com.nukive.renderprotocol.ui.v1.RPAction value) {
      if (onLongPressBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          onLongPress_ != null &&
          onLongPress_ != com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance()) {
          getOnLongPressBuilder().mergeFrom(value);
        } else {
          onLongPress_ = value;
        }
      } else {
        onLongPressBuilder_.mergeFrom(value);
      }
      if (onLongPress_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     */
    public Builder clearOnLongPress() {
      bitField0_ = (bitField0_ & ~0x00000004);
      onLongPress_ = null;
      if (onLongPressBuilder_ != null) {
        onLongPressBuilder_.dispose();
        onLongPressBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPAction.Builder getOnLongPressBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetOnLongPressFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getOnLongPressOrBuilder() {
      if (onLongPressBuilder_ != null) {
        return onLongPressBuilder_.getMessageOrBuilder();
      } else {
        return onLongPress_ == null ?
            com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onLongPress_;
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_long_press = 3 [json_name = "onLongPress"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder> 
        internalGetOnLongPressFieldBuilder() {
      if (onLongPressBuilder_ == null) {
        onLongPressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder>(
                getOnLongPress(),
                getParentForChildren(),
                isClean());
        onLongPress_ = null;
      }
      return onLongPressBuilder_;
    }

    private com.nukive.renderprotocol.ui.v1.RPAction onDoubleTap_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder> onDoubleTapBuilder_;
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     * @return Whether the onDoubleTap field is set.
     */
    public boolean hasOnDoubleTap() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     * @return The onDoubleTap.
     */
    public com.nukive.renderprotocol.ui.v1.RPAction getOnDoubleTap() {
      if (onDoubleTapBuilder_ == null) {
        return onDoubleTap_ == null ? com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onDoubleTap_;
      } else {
        return onDoubleTapBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     */
    public Builder setOnDoubleTap(com.nukive.renderprotocol.ui.v1.RPAction value) {
      if (onDoubleTapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        onDoubleTap_ = value;
      } else {
        onDoubleTapBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     */
    public Builder setOnDoubleTap(
        com.nukive.renderprotocol.ui.v1.RPAction.Builder builderForValue) {
      if (onDoubleTapBuilder_ == null) {
        onDoubleTap_ = builderForValue.build();
      } else {
        onDoubleTapBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     */
    public Builder mergeOnDoubleTap(com.nukive.renderprotocol.ui.v1.RPAction value) {
      if (onDoubleTapBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          onDoubleTap_ != null &&
          onDoubleTap_ != com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance()) {
          getOnDoubleTapBuilder().mergeFrom(value);
        } else {
          onDoubleTap_ = value;
        }
      } else {
        onDoubleTapBuilder_.mergeFrom(value);
      }
      if (onDoubleTap_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     */
    public Builder clearOnDoubleTap() {
      bitField0_ = (bitField0_ & ~0x00000008);
      onDoubleTap_ = null;
      if (onDoubleTapBuilder_ != null) {
        onDoubleTapBuilder_.dispose();
        onDoubleTapBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPAction.Builder getOnDoubleTapBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetOnDoubleTapFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getOnDoubleTapOrBuilder() {
      if (onDoubleTapBuilder_ != null) {
        return onDoubleTapBuilder_.getMessageOrBuilder();
      } else {
        return onDoubleTap_ == null ?
            com.nukive.renderprotocol.ui.v1.RPAction.getDefaultInstance() : onDoubleTap_;
      }
    }
    /**
     * <code>optional .proto.renderprotocol.ui.v1.RPAction on_double_tap = 4 [json_name = "onDoubleTap"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder> 
        internalGetOnDoubleTapFieldBuilder() {
      if (onDoubleTapBuilder_ == null) {
        onDoubleTapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPAction, com.nukive.renderprotocol.ui.v1.RPAction.Builder, com.nukive.renderprotocol.ui.v1.RPActionOrBuilder>(
                getOnDoubleTap(),
                getParentForChildren(),
                isClean());
        onDoubleTap_ = null;
      }
      return onDoubleTapBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.renderprotocol.ui.v1.RPGestureDetector)
  }

  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPGestureDetector)
  private static final com.nukive.renderprotocol.ui.v1.RPGestureDetector DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nukive.renderprotocol.ui.v1.RPGestureDetector();
  }

  public static com.nukive.renderprotocol.ui.v1.RPGestureDetector getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPGestureDetector>
      PARSER = new com.google.protobuf.AbstractParser<RPGestureDetector>() {
    @java.lang.Override
    public RPGestureDetector parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPGestureDetector> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPGestureDetector> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPGestureDetector getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

