// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_color.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

/**
 * Protobuf type {@code proto.renderprotocol.ui.v1.RPGradientStop}
 */
@com.google.protobuf.Generated
public final class RPGradientStop extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.renderprotocol.ui.v1.RPGradientStop)
    RPGradientStopOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPGradientStop");
  }
  // Use RPGradientStop.newBuilder() to construct.
  private RPGradientStop(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPGradientStop() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nukive.renderprotocol.ui.v1.RpUiColorProto.internal_static_proto_renderprotocol_ui_v1_RPGradientStop_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nukive.renderprotocol.ui.v1.RpUiColorProto.internal_static_proto_renderprotocol_ui_v1_RPGradientStop_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nukive.renderprotocol.ui.v1.RpUiColorProto.internal_static_proto_renderprotocol_ui_v1_RPGradientStop_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nukive.renderprotocol.ui.v1.RPGradientStop.class, com.nukive.renderprotocol.ui.v1.RPGradientStop.Builder.class);
  }

  private int bitField0_;
  public static final int COLOR_FIELD_NUMBER = 1;
  private com.nukive.renderprotocol.ui.v1.RPColor color_;
  /**
   * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
   * @return Whether the color field is set.
   */
  @java.lang.Override
  public boolean hasColor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
   * @return The color.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPColor getColor() {
    return color_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : color_;
  }
  /**
   * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPColorOrBuilder getColorOrBuilder() {
    return color_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : color_;
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private float position_ = 0F;
  /**
   * <code>float position = 2 [json_name = "position"];</code>
   * @return The position.
   */
  @java.lang.Override
  public float getPosition() {
    return position_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getColor());
    }
    if (java.lang.Float.floatToRawIntBits(position_) != 0) {
      output.writeFloat(2, position_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getColor());
    }
    if (java.lang.Float.floatToRawIntBits(position_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, position_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nukive.renderprotocol.ui.v1.RPGradientStop)) {
      return super.equals(obj);
    }
    com.nukive.renderprotocol.ui.v1.RPGradientStop other = (com.nukive.renderprotocol.ui.v1.RPGradientStop) obj;

    if (hasColor() != other.hasColor()) return false;
    if (hasColor()) {
      if (!getColor()
          .equals(other.getColor())) return false;
    }
    if (java.lang.Float.floatToIntBits(getPosition())
        != java.lang.Float.floatToIntBits(
            other.getPosition())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasColor()) {
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
    }
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPosition());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.ui.v1.RPGradientStop parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nukive.renderprotocol.ui.v1.RPGradientStop prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.renderprotocol.ui.v1.RPGradientStop}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.renderprotocol.ui.v1.RPGradientStop)
      com.nukive.renderprotocol.ui.v1.RPGradientStopOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nukive.renderprotocol.ui.v1.RpUiColorProto.internal_static_proto_renderprotocol_ui_v1_RPGradientStop_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nukive.renderprotocol.ui.v1.RpUiColorProto.internal_static_proto_renderprotocol_ui_v1_RPGradientStop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nukive.renderprotocol.ui.v1.RPGradientStop.class, com.nukive.renderprotocol.ui.v1.RPGradientStop.Builder.class);
    }

    // Construct using com.nukive.renderprotocol.ui.v1.RPGradientStop.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetColorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      color_ = null;
      if (colorBuilder_ != null) {
        colorBuilder_.dispose();
        colorBuilder_ = null;
      }
      position_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nukive.renderprotocol.ui.v1.RpUiColorProto.internal_static_proto_renderprotocol_ui_v1_RPGradientStop_descriptor;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPGradientStop getDefaultInstanceForType() {
      return com.nukive.renderprotocol.ui.v1.RPGradientStop.getDefaultInstance();
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPGradientStop build() {
      com.nukive.renderprotocol.ui.v1.RPGradientStop result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.ui.v1.RPGradientStop buildPartial() {
      com.nukive.renderprotocol.ui.v1.RPGradientStop result = new com.nukive.renderprotocol.ui.v1.RPGradientStop(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nukive.renderprotocol.ui.v1.RPGradientStop result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.color_ = colorBuilder_ == null
            ? color_
            : colorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.position_ = position_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nukive.renderprotocol.ui.v1.RPGradientStop) {
        return mergeFrom((com.nukive.renderprotocol.ui.v1.RPGradientStop)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nukive.renderprotocol.ui.v1.RPGradientStop other) {
      if (other == com.nukive.renderprotocol.ui.v1.RPGradientStop.getDefaultInstance()) return this;
      if (other.hasColor()) {
        mergeColor(other.getColor());
      }
      if (java.lang.Float.floatToRawIntBits(other.getPosition()) != 0) {
        setPosition(other.getPosition());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              position_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.nukive.renderprotocol.ui.v1.RPColor color_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder> colorBuilder_;
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     * @return Whether the color field is set.
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     * @return The color.
     */
    public com.nukive.renderprotocol.ui.v1.RPColor getColor() {
      if (colorBuilder_ == null) {
        return color_ == null ? com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : color_;
      } else {
        return colorBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     */
    public Builder setColor(com.nukive.renderprotocol.ui.v1.RPColor value) {
      if (colorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        color_ = value;
      } else {
        colorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     */
    public Builder setColor(
        com.nukive.renderprotocol.ui.v1.RPColor.Builder builderForValue) {
      if (colorBuilder_ == null) {
        color_ = builderForValue.build();
      } else {
        colorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     */
    public Builder mergeColor(com.nukive.renderprotocol.ui.v1.RPColor value) {
      if (colorBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          color_ != null &&
          color_ != com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance()) {
          getColorBuilder().mergeFrom(value);
        } else {
          color_ = value;
        }
      } else {
        colorBuilder_.mergeFrom(value);
      }
      if (color_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     */
    public Builder clearColor() {
      bitField0_ = (bitField0_ & ~0x00000001);
      color_ = null;
      if (colorBuilder_ != null) {
        colorBuilder_.dispose();
        colorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPColor.Builder getColorBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     */
    public com.nukive.renderprotocol.ui.v1.RPColorOrBuilder getColorOrBuilder() {
      if (colorBuilder_ != null) {
        return colorBuilder_.getMessageOrBuilder();
      } else {
        return color_ == null ?
            com.nukive.renderprotocol.ui.v1.RPColor.getDefaultInstance() : color_;
      }
    }
    /**
     * <code>.proto.renderprotocol.ui.v1.RPColor color = 1 [json_name = "color"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder> 
        internalGetColorFieldBuilder() {
      if (colorBuilder_ == null) {
        colorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.ui.v1.RPColor, com.nukive.renderprotocol.ui.v1.RPColor.Builder, com.nukive.renderprotocol.ui.v1.RPColorOrBuilder>(
                getColor(),
                getParentForChildren(),
                isClean());
        color_ = null;
      }
      return colorBuilder_;
    }

    private float position_ ;
    /**
     * <code>float position = 2 [json_name = "position"];</code>
     * @return The position.
     */
    @java.lang.Override
    public float getPosition() {
      return position_;
    }
    /**
     * <code>float position = 2 [json_name = "position"];</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(float value) {

      position_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float position = 2 [json_name = "position"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      position_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.renderprotocol.ui.v1.RPGradientStop)
  }

  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPGradientStop)
  private static final com.nukive.renderprotocol.ui.v1.RPGradientStop DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nukive.renderprotocol.ui.v1.RPGradientStop();
  }

  public static com.nukive.renderprotocol.ui.v1.RPGradientStop getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPGradientStop>
      PARSER = new com.google.protobuf.AbstractParser<RPGradientStop>() {
    @java.lang.Override
    public RPGradientStop parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPGradientStop> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPGradientStop> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nukive.renderprotocol.ui.v1.RPGradientStop getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

