// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_icon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPIcon")
public inline fun rPIcon(block: com.nukive.renderprotocol.ui.v1.RPIconKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPIcon =
  com.nukive.renderprotocol.ui.v1.RPIconKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPIcon.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPIcon`
 */
public object RPIconKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPIcon.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPIcon.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPIcon = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `optional float size = 2 [json_name = "size"];`
     */
    public var size: kotlin.Float
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `optional float size = 2 [json_name = "size"];`
     */
    public fun clearSize() {
      _builder.clearSize()
    }
    /**
     * `optional float size = 2 [json_name = "size"];`
     * @return Whether the size field is set.
     */
    public fun hasSize(): kotlin.Boolean {
      return _builder.hasSize()
    }

    /**
     * `optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];`
     */
    public var color: com.nukive.renderprotocol.ui.v1.RPColor
      @kotlin.jvm.JvmName("getColor")
        get() = _builder.color
      @kotlin.jvm.JvmName("setColor")
        set(value) {
        _builder.color = value
      }
    /**
     * `optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];`
     */
    public fun clearColor() {
      _builder.clearColor()
    }
    /**
     * `optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];`
     * @return Whether the color field is set.
     */
    public fun hasColor(): kotlin.Boolean {
      return _builder.hasColor()
    }

    public val RPIconKt.Dsl.colorOrNull: com.nukive.renderprotocol.ui.v1.RPColor?
      get() = _builder.colorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPIcon.copy(block: `com.nukive.renderprotocol.ui.v1`.RPIconKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPIcon =
  `com.nukive.renderprotocol.ui.v1`.RPIconKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPIconOrBuilder.colorOrNull: com.nukive.renderprotocol.ui.v1.RPColor?
  get() = if (hasColor()) getColor() else null

