// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_image.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPImage")
public inline fun rPImage(block: com.nukive.renderprotocol.ui.v1.RPImageKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPImage =
  com.nukive.renderprotocol.ui.v1.RPImageKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPImage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPImage`
 */
public object RPImageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPImage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPImage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPImage = _builder.build()

    /**
     * `string url = 1 [json_name = "url"];`
     */
    public var url: kotlin.String
      @kotlin.jvm.JvmName("getUrl")
        get() = _builder.url
      @kotlin.jvm.JvmName("setUrl")
        set(value) {
        _builder.url = value
      }
    /**
     * `string url = 1 [json_name = "url"];`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * `optional float width = 2 [json_name = "width"];`
     */
    public var width: kotlin.Float
      @kotlin.jvm.JvmName("getWidth")
        get() = _builder.width
      @kotlin.jvm.JvmName("setWidth")
        set(value) {
        _builder.width = value
      }
    /**
     * `optional float width = 2 [json_name = "width"];`
     */
    public fun clearWidth() {
      _builder.clearWidth()
    }
    /**
     * `optional float width = 2 [json_name = "width"];`
     * @return Whether the width field is set.
     */
    public fun hasWidth(): kotlin.Boolean {
      return _builder.hasWidth()
    }

    /**
     * `optional float height = 3 [json_name = "height"];`
     */
    public var height: kotlin.Float
      @kotlin.jvm.JvmName("getHeight")
        get() = _builder.height
      @kotlin.jvm.JvmName("setHeight")
        set(value) {
        _builder.height = value
      }
    /**
     * `optional float height = 3 [json_name = "height"];`
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }
    /**
     * `optional float height = 3 [json_name = "height"];`
     * @return Whether the height field is set.
     */
    public fun hasHeight(): kotlin.Boolean {
      return _builder.hasHeight()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPContentMode content_mode = 4 [json_name = "contentMode"];`
     */
    public var contentMode: com.nukive.renderprotocol.ui.v1.RPContentMode
      @kotlin.jvm.JvmName("getContentMode")
        get() = _builder.contentMode
      @kotlin.jvm.JvmName("setContentMode")
        set(value) {
        _builder.contentMode = value
      }
    public var contentModeValue: kotlin.Int
      @kotlin.jvm.JvmName("getContentModeValue")
        get() = _builder.contentModeValue
      @kotlin.jvm.JvmName("setContentModeValue")
        set(value) {
        _builder.contentModeValue = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPContentMode content_mode = 4 [json_name = "contentMode"];`
     */
    public fun clearContentMode() {
      _builder.clearContentMode()
    }

    /**
     * `optional string placeholder_url = 5 [json_name = "placeholderUrl"];`
     */
    public var placeholderUrl: kotlin.String
      @kotlin.jvm.JvmName("getPlaceholderUrl")
        get() = _builder.placeholderUrl
      @kotlin.jvm.JvmName("setPlaceholderUrl")
        set(value) {
        _builder.placeholderUrl = value
      }
    /**
     * `optional string placeholder_url = 5 [json_name = "placeholderUrl"];`
     */
    public fun clearPlaceholderUrl() {
      _builder.clearPlaceholderUrl()
    }
    /**
     * `optional string placeholder_url = 5 [json_name = "placeholderUrl"];`
     * @return Whether the placeholderUrl field is set.
     */
    public fun hasPlaceholderUrl(): kotlin.Boolean {
      return _builder.hasPlaceholderUrl()
    }

    /**
     * `optional .proto.renderprotocol.ui.v1.RPColor tint_color = 6 [json_name = "tintColor"];`
     */
    public var tintColor: com.nukive.renderprotocol.ui.v1.RPColor
      @kotlin.jvm.JvmName("getTintColor")
        get() = _builder.tintColor
      @kotlin.jvm.JvmName("setTintColor")
        set(value) {
        _builder.tintColor = value
      }
    /**
     * `optional .proto.renderprotocol.ui.v1.RPColor tint_color = 6 [json_name = "tintColor"];`
     */
    public fun clearTintColor() {
      _builder.clearTintColor()
    }
    /**
     * `optional .proto.renderprotocol.ui.v1.RPColor tint_color = 6 [json_name = "tintColor"];`
     * @return Whether the tintColor field is set.
     */
    public fun hasTintColor(): kotlin.Boolean {
      return _builder.hasTintColor()
    }

    public val RPImageKt.Dsl.tintColorOrNull: com.nukive.renderprotocol.ui.v1.RPColor?
      get() = _builder.tintColorOrNull

    /**
     * `optional string alt_text = 7 [json_name = "altText"];`
     */
    public var altText: kotlin.String
      @kotlin.jvm.JvmName("getAltText")
        get() = _builder.altText
      @kotlin.jvm.JvmName("setAltText")
        set(value) {
        _builder.altText = value
      }
    /**
     * `optional string alt_text = 7 [json_name = "altText"];`
     */
    public fun clearAltText() {
      _builder.clearAltText()
    }
    /**
     * `optional string alt_text = 7 [json_name = "altText"];`
     * @return Whether the altText field is set.
     */
    public fun hasAltText(): kotlin.Boolean {
      return _builder.hasAltText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPImage.copy(block: `com.nukive.renderprotocol.ui.v1`.RPImageKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPImage =
  `com.nukive.renderprotocol.ui.v1`.RPImageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPImageOrBuilder.tintColorOrNull: com.nukive.renderprotocol.ui.v1.RPColor?
  get() = if (hasTintColor()) getTintColor() else null

