// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPOpacity")
public inline fun rPOpacity(block: com.nukive.renderprotocol.ui.v1.RPOpacityKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPOpacity =
  com.nukive.renderprotocol.ui.v1.RPOpacityKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPOpacity.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPOpacity`
 */
public object RPOpacityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPOpacity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPOpacity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPOpacity = _builder.build()

    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     */
    public var child: com.nukive.renderprotocol.ui.v1.RPWidget
      @kotlin.jvm.JvmName("getChild")
        get() = _builder.child
      @kotlin.jvm.JvmName("setChild")
        set(value) {
        _builder.child = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     */
    public fun clearChild() {
      _builder.clearChild()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     * @return Whether the child field is set.
     */
    public fun hasChild(): kotlin.Boolean {
      return _builder.hasChild()
    }

    public val RPOpacityKt.Dsl.childOrNull: com.nukive.renderprotocol.ui.v1.RPWidget?
      get() = _builder.childOrNull

    /**
     * `float value = 2 [json_name = "value"];`
     */
    public var value: kotlin.Float
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * `float value = 2 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPOpacity.copy(block: `com.nukive.renderprotocol.ui.v1`.RPOpacityKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPOpacity =
  `com.nukive.renderprotocol.ui.v1`.RPOpacityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPOpacityOrBuilder.childOrNull: com.nukive.renderprotocol.ui.v1.RPWidget?
  get() = if (hasChild()) getChild() else null

