// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPPositioned")
public inline fun rPPositioned(block: com.nukive.renderprotocol.ui.v1.RPPositionedKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPPositioned =
  com.nukive.renderprotocol.ui.v1.RPPositionedKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPPositioned.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPPositioned`
 */
public object RPPositionedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPPositioned.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPPositioned.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPPositioned = _builder.build()

    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     */
    public var child: com.nukive.renderprotocol.ui.v1.RPWidget
      @kotlin.jvm.JvmName("getChild")
        get() = _builder.child
      @kotlin.jvm.JvmName("setChild")
        set(value) {
        _builder.child = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     */
    public fun clearChild() {
      _builder.clearChild()
    }
    /**
     * `.proto.renderprotocol.ui.v1.RPWidget child = 1 [json_name = "child"];`
     * @return Whether the child field is set.
     */
    public fun hasChild(): kotlin.Boolean {
      return _builder.hasChild()
    }

    public val RPPositionedKt.Dsl.childOrNull: com.nukive.renderprotocol.ui.v1.RPWidget?
      get() = _builder.childOrNull

    /**
     * `optional float top = 2 [json_name = "top"];`
     */
    public var top: kotlin.Float
      @kotlin.jvm.JvmName("getTop")
        get() = _builder.top
      @kotlin.jvm.JvmName("setTop")
        set(value) {
        _builder.top = value
      }
    /**
     * `optional float top = 2 [json_name = "top"];`
     */
    public fun clearTop() {
      _builder.clearTop()
    }
    /**
     * `optional float top = 2 [json_name = "top"];`
     * @return Whether the top field is set.
     */
    public fun hasTop(): kotlin.Boolean {
      return _builder.hasTop()
    }

    /**
     * `optional float bottom = 3 [json_name = "bottom"];`
     */
    public var bottom: kotlin.Float
      @kotlin.jvm.JvmName("getBottom")
        get() = _builder.bottom
      @kotlin.jvm.JvmName("setBottom")
        set(value) {
        _builder.bottom = value
      }
    /**
     * `optional float bottom = 3 [json_name = "bottom"];`
     */
    public fun clearBottom() {
      _builder.clearBottom()
    }
    /**
     * `optional float bottom = 3 [json_name = "bottom"];`
     * @return Whether the bottom field is set.
     */
    public fun hasBottom(): kotlin.Boolean {
      return _builder.hasBottom()
    }

    /**
     * `optional float leading = 4 [json_name = "leading"];`
     */
    public var leading: kotlin.Float
      @kotlin.jvm.JvmName("getLeading")
        get() = _builder.leading
      @kotlin.jvm.JvmName("setLeading")
        set(value) {
        _builder.leading = value
      }
    /**
     * `optional float leading = 4 [json_name = "leading"];`
     */
    public fun clearLeading() {
      _builder.clearLeading()
    }
    /**
     * `optional float leading = 4 [json_name = "leading"];`
     * @return Whether the leading field is set.
     */
    public fun hasLeading(): kotlin.Boolean {
      return _builder.hasLeading()
    }

    /**
     * `optional float trailing = 5 [json_name = "trailing"];`
     */
    public var trailing: kotlin.Float
      @kotlin.jvm.JvmName("getTrailing")
        get() = _builder.trailing
      @kotlin.jvm.JvmName("setTrailing")
        set(value) {
        _builder.trailing = value
      }
    /**
     * `optional float trailing = 5 [json_name = "trailing"];`
     */
    public fun clearTrailing() {
      _builder.clearTrailing()
    }
    /**
     * `optional float trailing = 5 [json_name = "trailing"];`
     * @return Whether the trailing field is set.
     */
    public fun hasTrailing(): kotlin.Boolean {
      return _builder.hasTrailing()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPPositioned.copy(block: `com.nukive.renderprotocol.ui.v1`.RPPositionedKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPPositioned =
  `com.nukive.renderprotocol.ui.v1`.RPPositionedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPPositionedOrBuilder.childOrNull: com.nukive.renderprotocol.ui.v1.RPWidget?
  get() = if (hasChild()) getChild() else null

