// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_shape.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPShapeCapsule")
public inline fun rPShapeCapsule(block: com.nukive.renderprotocol.ui.v1.RPShapeCapsuleKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPShapeCapsule =
  com.nukive.renderprotocol.ui.v1.RPShapeCapsuleKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPShapeCapsule.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPShapeCapsule`
 */
public object RPShapeCapsuleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPShapeCapsule.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPShapeCapsule.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPShapeCapsule = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPShapeCapsule.copy(block: `com.nukive.renderprotocol.ui.v1`.RPShapeCapsuleKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPShapeCapsule =
  `com.nukive.renderprotocol.ui.v1`.RPShapeCapsuleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

