// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core_support.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

@com.google.protobuf.Generated
public interface RPSizeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.renderprotocol.ui.v1.RPSize)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float width = 1 [json_name = "width"];</code>
   * @return The width.
   */
  float getWidth();

  /**
   * <code>float height = 2 [json_name = "height"];</code>
   * @return The height.
   */
  float getHeight();
}
