// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_text_field.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

@com.google.protobuf.Generated
public interface RPTextFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.renderprotocol.ui.v1.RPTextField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string field_id = 1 [json_name = "fieldId"];</code>
   * @return The fieldId.
   */
  java.lang.String getFieldId();
  /**
   * <code>string field_id = 1 [json_name = "fieldId"];</code>
   * @return The bytes for fieldId.
   */
  com.google.protobuf.ByteString
      getFieldIdBytes();

  /**
   * <code>optional string placeholder = 2 [json_name = "placeholder"];</code>
   * @return Whether the placeholder field is set.
   */
  boolean hasPlaceholder();
  /**
   * <code>optional string placeholder = 2 [json_name = "placeholder"];</code>
   * @return The placeholder.
   */
  java.lang.String getPlaceholder();
  /**
   * <code>optional string placeholder = 2 [json_name = "placeholder"];</code>
   * @return The bytes for placeholder.
   */
  com.google.protobuf.ByteString
      getPlaceholderBytes();

  /**
   * <code>optional string initial_value = 3 [json_name = "initialValue"];</code>
   * @return Whether the initialValue field is set.
   */
  boolean hasInitialValue();
  /**
   * <code>optional string initial_value = 3 [json_name = "initialValue"];</code>
   * @return The initialValue.
   */
  java.lang.String getInitialValue();
  /**
   * <code>optional string initial_value = 3 [json_name = "initialValue"];</code>
   * @return The bytes for initialValue.
   */
  com.google.protobuf.ByteString
      getInitialValueBytes();

  /**
   * <code>.proto.renderprotocol.ui.v1.RPKeyboardType keyboard_type = 4 [json_name = "keyboardType"];</code>
   * @return The enum numeric value on the wire for keyboardType.
   */
  int getKeyboardTypeValue();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPKeyboardType keyboard_type = 4 [json_name = "keyboardType"];</code>
   * @return The keyboardType.
   */
  com.nukive.renderprotocol.ui.v1.RPKeyboardType getKeyboardType();

  /**
   * <code>bool secure_entry = 5 [json_name = "secureEntry"];</code>
   * @return The secureEntry.
   */
  boolean getSecureEntry();

  /**
   * <code>optional int32 max_length = 6 [json_name = "maxLength"];</code>
   * @return Whether the maxLength field is set.
   */
  boolean hasMaxLength();
  /**
   * <code>optional int32 max_length = 6 [json_name = "maxLength"];</code>
   * @return The maxLength.
   */
  int getMaxLength();

  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];</code>
   * @return Whether the textStyle field is set.
   */
  boolean hasTextStyle();
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];</code>
   * @return The textStyle.
   */
  com.nukive.renderprotocol.ui.v1.RPTextStyle getTextStyle();
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];</code>
   */
  com.nukive.renderprotocol.ui.v1.RPTextStyleOrBuilder getTextStyleOrBuilder();

  /**
   * <code>bool enabled = 8 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];</code>
   * @return Whether the onSubmit field is set.
   */
  boolean hasOnSubmit();
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];</code>
   * @return The onSubmit.
   */
  com.nukive.renderprotocol.ui.v1.RPAction getOnSubmit();
  /**
   * <code>optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];</code>
   */
  com.nukive.renderprotocol.ui.v1.RPActionOrBuilder getOnSubmitOrBuilder();
}
