// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_text_field.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.ui.v1;

@kotlin.jvm.JvmName("-initializerPTextField")
public inline fun rPTextField(block: com.nukive.renderprotocol.ui.v1.RPTextFieldKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPTextField =
  com.nukive.renderprotocol.ui.v1.RPTextFieldKt.Dsl._create(com.nukive.renderprotocol.ui.v1.RPTextField.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.ui.v1.RPTextField`
 */
public object RPTextFieldKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.ui.v1.RPTextField.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.ui.v1.RPTextField.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.ui.v1.RPTextField = _builder.build()

    /**
     * `string field_id = 1 [json_name = "fieldId"];`
     */
    public var fieldId: kotlin.String
      @kotlin.jvm.JvmName("getFieldId")
        get() = _builder.fieldId
      @kotlin.jvm.JvmName("setFieldId")
        set(value) {
        _builder.fieldId = value
      }
    /**
     * `string field_id = 1 [json_name = "fieldId"];`
     */
    public fun clearFieldId() {
      _builder.clearFieldId()
    }

    /**
     * `optional string placeholder = 2 [json_name = "placeholder"];`
     */
    public var placeholder: kotlin.String
      @kotlin.jvm.JvmName("getPlaceholder")
        get() = _builder.placeholder
      @kotlin.jvm.JvmName("setPlaceholder")
        set(value) {
        _builder.placeholder = value
      }
    /**
     * `optional string placeholder = 2 [json_name = "placeholder"];`
     */
    public fun clearPlaceholder() {
      _builder.clearPlaceholder()
    }
    /**
     * `optional string placeholder = 2 [json_name = "placeholder"];`
     * @return Whether the placeholder field is set.
     */
    public fun hasPlaceholder(): kotlin.Boolean {
      return _builder.hasPlaceholder()
    }

    /**
     * `optional string initial_value = 3 [json_name = "initialValue"];`
     */
    public var initialValue: kotlin.String
      @kotlin.jvm.JvmName("getInitialValue")
        get() = _builder.initialValue
      @kotlin.jvm.JvmName("setInitialValue")
        set(value) {
        _builder.initialValue = value
      }
    /**
     * `optional string initial_value = 3 [json_name = "initialValue"];`
     */
    public fun clearInitialValue() {
      _builder.clearInitialValue()
    }
    /**
     * `optional string initial_value = 3 [json_name = "initialValue"];`
     * @return Whether the initialValue field is set.
     */
    public fun hasInitialValue(): kotlin.Boolean {
      return _builder.hasInitialValue()
    }

    /**
     * `.proto.renderprotocol.ui.v1.RPKeyboardType keyboard_type = 4 [json_name = "keyboardType"];`
     */
    public var keyboardType: com.nukive.renderprotocol.ui.v1.RPKeyboardType
      @kotlin.jvm.JvmName("getKeyboardType")
        get() = _builder.keyboardType
      @kotlin.jvm.JvmName("setKeyboardType")
        set(value) {
        _builder.keyboardType = value
      }
    public var keyboardTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getKeyboardTypeValue")
        get() = _builder.keyboardTypeValue
      @kotlin.jvm.JvmName("setKeyboardTypeValue")
        set(value) {
        _builder.keyboardTypeValue = value
      }
    /**
     * `.proto.renderprotocol.ui.v1.RPKeyboardType keyboard_type = 4 [json_name = "keyboardType"];`
     */
    public fun clearKeyboardType() {
      _builder.clearKeyboardType()
    }

    /**
     * `bool secure_entry = 5 [json_name = "secureEntry"];`
     */
    public var secureEntry: kotlin.Boolean
      @kotlin.jvm.JvmName("getSecureEntry")
        get() = _builder.secureEntry
      @kotlin.jvm.JvmName("setSecureEntry")
        set(value) {
        _builder.secureEntry = value
      }
    /**
     * `bool secure_entry = 5 [json_name = "secureEntry"];`
     */
    public fun clearSecureEntry() {
      _builder.clearSecureEntry()
    }

    /**
     * `optional int32 max_length = 6 [json_name = "maxLength"];`
     */
    public var maxLength: kotlin.Int
      @kotlin.jvm.JvmName("getMaxLength")
        get() = _builder.maxLength
      @kotlin.jvm.JvmName("setMaxLength")
        set(value) {
        _builder.maxLength = value
      }
    /**
     * `optional int32 max_length = 6 [json_name = "maxLength"];`
     */
    public fun clearMaxLength() {
      _builder.clearMaxLength()
    }
    /**
     * `optional int32 max_length = 6 [json_name = "maxLength"];`
     * @return Whether the maxLength field is set.
     */
    public fun hasMaxLength(): kotlin.Boolean {
      return _builder.hasMaxLength()
    }

    /**
     * `optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];`
     */
    public var textStyle: com.nukive.renderprotocol.ui.v1.RPTextStyle
      @kotlin.jvm.JvmName("getTextStyle")
        get() = _builder.textStyle
      @kotlin.jvm.JvmName("setTextStyle")
        set(value) {
        _builder.textStyle = value
      }
    /**
     * `optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];`
     */
    public fun clearTextStyle() {
      _builder.clearTextStyle()
    }
    /**
     * `optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];`
     * @return Whether the textStyle field is set.
     */
    public fun hasTextStyle(): kotlin.Boolean {
      return _builder.hasTextStyle()
    }

    public val RPTextFieldKt.Dsl.textStyleOrNull: com.nukive.renderprotocol.ui.v1.RPTextStyle?
      get() = _builder.textStyleOrNull

    /**
     * `bool enabled = 8 [json_name = "enabled"];`
     */
    public var enabled: kotlin.Boolean
      @kotlin.jvm.JvmName("getEnabled")
        get() = _builder.enabled
      @kotlin.jvm.JvmName("setEnabled")
        set(value) {
        _builder.enabled = value
      }
    /**
     * `bool enabled = 8 [json_name = "enabled"];`
     */
    public fun clearEnabled() {
      _builder.clearEnabled()
    }

    /**
     * `optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];`
     */
    public var onSubmit: com.nukive.renderprotocol.ui.v1.RPAction
      @kotlin.jvm.JvmName("getOnSubmit")
        get() = _builder.onSubmit
      @kotlin.jvm.JvmName("setOnSubmit")
        set(value) {
        _builder.onSubmit = value
      }
    /**
     * `optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];`
     */
    public fun clearOnSubmit() {
      _builder.clearOnSubmit()
    }
    /**
     * `optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];`
     * @return Whether the onSubmit field is set.
     */
    public fun hasOnSubmit(): kotlin.Boolean {
      return _builder.hasOnSubmit()
    }

    public val RPTextFieldKt.Dsl.onSubmitOrNull: com.nukive.renderprotocol.ui.v1.RPAction?
      get() = _builder.onSubmitOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.ui.v1.RPTextField.copy(block: `com.nukive.renderprotocol.ui.v1`.RPTextFieldKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.ui.v1.RPTextField =
  `com.nukive.renderprotocol.ui.v1`.RPTextFieldKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.ui.v1.RPTextFieldOrBuilder.textStyleOrNull: com.nukive.renderprotocol.ui.v1.RPTextStyle?
  get() = if (hasTextStyle()) getTextStyle() else null

public val com.nukive.renderprotocol.ui.v1.RPTextFieldOrBuilder.onSubmitOrNull: com.nukive.renderprotocol.ui.v1.RPAction?
  get() = if (hasOnSubmit()) getOnSubmit() else null

