// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_core.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

@com.google.protobuf.Generated
public final class RpUiCoreProto extends com.google.protobuf.GeneratedFile {
  private RpUiCoreProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RpUiCoreProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPWidget_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPWidget_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPColumn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPColumn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPStack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPStack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPScrollable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPScrollable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPLazyList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPLazyList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPLazyGrid_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPLazyGrid_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPWrap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPWrap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPCenter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPCenter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPExpanded_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPExpanded_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPPadding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPPadding_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPBackground_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPBackground_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPBorder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPBorder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPClip_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPClip_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPOpacity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPOpacity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPVisibility_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPVisibility_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPShadow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPShadow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPSizeBox_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPSizeBox_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPSafeArea_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPSafeArea_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPAspectRatio_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPAspectRatio_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPPositioned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPPositioned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPButton_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPButton_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPToggle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPToggle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPCard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPCard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPListTile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPListTile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPAppBar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPAppBar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPBadge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPBadge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPScaffold_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPScaffold_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+proto/renderprotocol/ui/v1/rp_ui_core." +
      "proto\022\032proto.renderprotocol.ui.v1\032-proto" +
      "/renderprotocol/ui/v1/rp_ui_action.proto" +
      "\0325proto/renderprotocol/ui/v1/rp_ui_botto" +
      "m_nav_bar.proto\032,proto/renderprotocol/ui" +
      "/v1/rp_ui_color.proto\0323proto/renderproto" +
      "col/ui/v1/rp_ui_core_support.proto\032.prot" +
      "o/renderprotocol/ui/v1/rp_ui_divider.pro" +
      "to\032+proto/renderprotocol/ui/v1/rp_ui_ico" +
      "n.proto\032,proto/renderprotocol/ui/v1/rp_u" +
      "i_image.proto\0329proto/renderprotocol/ui/v" +
      "1/rp_ui_progress_indicator.proto\032-proto/" +
      "renderprotocol/ui/v1/rp_ui_slider.proto\032" +
      "-proto/renderprotocol/ui/v1/rp_ui_spacer" +
      ".proto\032+proto/renderprotocol/ui/v1/rp_ui" +
      "_text.proto\0321proto/renderprotocol/ui/v1/" +
      "rp_ui_text_field.proto\"\221\024\n\010RPWidget\022\016\n\002i" +
      "d\030\001 \001(\tR\002id\0225\n\003row\0303 \001(\0132!.proto.renderp" +
      "rotocol.ui.v1.RPRowH\000R\003row\022>\n\006column\0304 \001" +
      "(\0132$.proto.renderprotocol.ui.v1.RPColumn" +
      "H\000R\006column\022;\n\005stack\0305 \001(\0132#.proto.render" +
      "protocol.ui.v1.RPStackH\000R\005stack\022J\n\nscrol" +
      "lable\030: \001(\0132(.proto.renderprotocol.ui.v1" +
      ".RPScrollableH\000R\nscrollable\022E\n\tlazy_list" +
      "\030; \001(\0132&.proto.renderprotocol.ui.v1.RPLa" +
      "zyListH\000R\010lazyList\022E\n\tlazy_grid\030< \001(\0132&." +
      "proto.renderprotocol.ui.v1.RPLazyGridH\000R" +
      "\010lazyGrid\0228\n\004wrap\030= \001(\0132\".proto.renderpr" +
      "otocol.ui.v1.RPWrapH\000R\004wrap\022>\n\006center\030> " +
      "\001(\0132$.proto.renderprotocol.ui.v1.RPCente" +
      "rH\000R\006center\022D\n\010expanded\030? \001(\0132&.proto.re" +
      "nderprotocol.ui.v1.RPExpandedH\000R\010expande" +
      "d\022A\n\007padding\030F \001(\0132%.proto.renderprotoco" +
      "l.ui.v1.RPPaddingH\000R\007padding\022J\n\nbackgrou" +
      "nd\030G \001(\0132(.proto.renderprotocol.ui.v1.RP" +
      "BackgroundH\000R\nbackground\022>\n\006border\030H \001(\013" +
      "2$.proto.renderprotocol.ui.v1.RPBorderH\000" +
      "R\006border\0228\n\004clip\030I \001(\0132\".proto.renderpro" +
      "tocol.ui.v1.RPClipH\000R\004clip\022A\n\007opacity\030J " +
      "\001(\0132%.proto.renderprotocol.ui.v1.RPOpaci" +
      "tyH\000R\007opacity\022J\n\nvisibility\030K \001(\0132(.prot" +
      "o.renderprotocol.ui.v1.RPVisibilityH\000R\nv" +
      "isibility\022>\n\006shadow\030L \001(\0132$.proto.render" +
      "protocol.ui.v1.RPShadowH\000R\006shadow\022B\n\010siz" +
      "e_box\030M \001(\0132%.proto.renderprotocol.ui.v1" +
      ".RPSizeBoxH\000R\007sizeBox\022E\n\tsafe_area\030N \001(\013" +
      "2&.proto.renderprotocol.ui.v1.RPSafeArea" +
      "H\000R\010safeArea\022N\n\014aspect_ratio\030O \001(\0132).pro" +
      "to.renderprotocol.ui.v1.RPAspectRatioH\000R" +
      "\013aspectRatio\022J\n\npositioned\030P \001(\0132(.proto" +
      ".renderprotocol.ui.v1.RPPositionedH\000R\npo" +
      "sitioned\0228\n\004text\030e \001(\0132\".proto.renderpro" +
      "tocol.ui.v1.RPTextH\000R\004text\022;\n\005image\030f \001(" +
      "\0132#.proto.renderprotocol.ui.v1.RPImageH\000" +
      "R\005image\0228\n\004icon\030g \001(\0132\".proto.renderprot" +
      "ocol.ui.v1.RPIconH\000R\004icon\022>\n\006spacer\030h \001(" +
      "\0132$.proto.renderprotocol.ui.v1.RPSpacerH" +
      "\000R\006spacer\022A\n\007divider\030i \001(\0132%.proto.rende" +
      "rprotocol.ui.v1.RPDividerH\000R\007divider\022`\n\022" +
      "progress_indicator\030j \001(\0132/.proto.renderp" +
      "rotocol.ui.v1.RPProgressIndicatorH\000R\021pro" +
      "gressIndicator\022>\n\006button\030k \001(\0132$.proto.r" +
      "enderprotocol.ui.v1.RPButtonH\000R\006button\022I" +
      "\n\ntext_field\030\226\001 \001(\0132\'.proto.renderprotoc" +
      "ol.ui.v1.RPTextFieldH\000R\ttextField\022?\n\006tog" +
      "gle\030\227\001 \001(\0132$.proto.renderprotocol.ui.v1." +
      "RPToggleH\000R\006toggle\022?\n\006slider\030\230\001 \001(\0132$.pr" +
      "oto.renderprotocol.ui.v1.RPSliderH\000R\006sli" +
      "der\0229\n\004card\030\264\001 \001(\0132\".proto.renderprotoco" +
      "l.ui.v1.RPCardH\000R\004card\022F\n\tlist_tile\030\265\001 \001" +
      "(\0132&.proto.renderprotocol.ui.v1.RPListTi" +
      "leH\000R\010listTile\022@\n\007app_bar\030\266\001 \001(\0132$.proto" +
      ".renderprotocol.ui.v1.RPAppBarH\000R\006appBar" +
      "\022S\n\016bottom_nav_bar\030\267\001 \001(\0132*.proto.render" +
      "protocol.ui.v1.RPBottomNavBarH\000R\014bottomN" +
      "avBar\022<\n\005badge\030\270\001 \001(\0132#.proto.renderprot" +
      "ocol.ui.v1.RPBadgeH\000R\005badge\022E\n\010scaffold\030" +
      "\271\001 \001(\0132&.proto.renderprotocol.ui.v1.RPSc" +
      "affoldH\000R\010scaffold\022[\n\020gesture_detector\030\310" +
      "\001 \001(\0132-.proto.renderprotocol.ui.v1.RPGes" +
      "tureDetectorH\000R\017gestureDetectorB\t\n\007conte" +
      "nt\"\256\001\n\005RPRow\022@\n\010children\030\001 \003(\0132$.proto.r" +
      "enderprotocol.ui.v1.RPWidgetR\010children\022\030" +
      "\n\007spacing\030\002 \001(\003R\007spacing\022I\n\talignment\030\003 " +
      "\001(\0162+.proto.renderprotocol.ui.v1.RPAxisA" +
      "lignmentR\talignment\"\261\001\n\010RPColumn\022@\n\010chil" +
      "dren\030\001 \003(\0132$.proto.renderprotocol.ui.v1." +
      "RPWidgetR\010children\022\030\n\007spacing\030\002 \001(\003R\007spa" +
      "cing\022I\n\talignment\030\003 \001(\0162+.proto.renderpr" +
      "otocol.ui.v1.RPAxisAlignmentR\talignment\"" +
      "\222\001\n\007RPStack\022@\n\010children\030\001 \003(\0132$.proto.re" +
      "nderprotocol.ui.v1.RPWidgetR\010children\022E\n" +
      "\talignment\030\002 \001(\0162\'.proto.renderprotocol." +
      "ui.v1.RPAlignmentR\talignment\"\255\001\n\014RPScrol" +
      "lable\022:\n\005child\030\001 \001(\0132$.proto.renderproto" +
      "col.ui.v1.RPWidgetR\005child\0226\n\004axis\030\002 \001(\0162" +
      "\".proto.renderprotocol.ui.v1.RPAxisR\004axi" +
      "s\022)\n\020shows_indicators\030\003 \001(\010R\017showsIndica" +
      "tors\"\242\002\n\nRPLazyList\022@\n\010children\030\001 \003(\0132$." +
      "proto.renderprotocol.ui.v1.RPWidgetR\010chi" +
      "ldren\0226\n\004axis\030\002 \001(\0162\".proto.renderprotoc" +
      "ol.ui.v1.RPAxisR\004axis\022\030\n\007spacing\030\003 \001(\002R\007" +
      "spacing\022)\n\020shows_indicators\030\004 \001(\010R\017shows" +
      "Indicators\022G\n\tseparator\030\005 \001(\0132$.proto.re" +
      "nderprotocol.ui.v1.RPWidgetH\000R\tseparator" +
      "\210\001\001B\014\n\n_separator\"\313\001\n\nRPLazyGrid\022@\n\010chil" +
      "dren\030\001 \003(\0132$.proto.renderprotocol.ui.v1." +
      "RPWidgetR\010children\022@\n\006layout\030\002 \001(\0132(.pro" +
      "to.renderprotocol.ui.v1.RPGridLayoutR\006la" +
      "yout\022\030\n\007spacing\030\003 \001(\002R\007spacing\022\037\n\013run_sp" +
      "acing\030\004 \001(\002R\nrunSpacing\"\314\001\n\006RPWrap\022@\n\010ch" +
      "ildren\030\001 \003(\0132$.proto.renderprotocol.ui.v" +
      "1.RPWidgetR\010children\022\030\n\007spacing\030\002 \001(\002R\007s" +
      "pacing\022\037\n\013run_spacing\030\003 \001(\002R\nrunSpacing\022" +
      "E\n\talignment\030\004 \001(\0162\'.proto.renderprotoco" +
      "l.ui.v1.RPAlignmentR\talignment\"F\n\010RPCent" +
      "er\022:\n\005child\030\001 \001(\0132$.proto.renderprotocol" +
      ".ui.v1.RPWidgetR\005child\"\\\n\nRPExpanded\022:\n\005" +
      "child\030\001 \001(\0132$.proto.renderprotocol.ui.v1" +
      ".RPWidgetR\005child\022\022\n\004flex\030\002 \001(\005R\004flex\"\201\002\n" +
      "\tRPPadding\022:\n\005child\030\001 \001(\0132$.proto.render" +
      "protocol.ui.v1.RPWidgetR\005child\022\022\n\003all\030\013 " +
      "\001(\002H\000R\003all\022N\n\tsymmetric\030\014 \001(\0132..proto.re" +
      "nderprotocol.ui.v1.RPSymmetricPaddingH\000R" +
      "\tsymmetric\022K\n\010explicit\030\r \001(\0132-.proto.ren" +
      "derprotocol.ui.v1.RPExplicitPaddingH\000R\010e" +
      "xplicitB\007\n\005value\"\205\001\n\014RPBackground\022:\n\005chi" +
      "ld\030\001 \001(\0132$.proto.renderprotocol.ui.v1.RP" +
      "WidgetR\005child\0229\n\005color\030\002 \001(\0132#.proto.ren" +
      "derprotocol.ui.v1.RPColorR\005color\"\277\001\n\010RPB" +
      "order\022:\n\005child\030\001 \001(\0132$.proto.renderproto" +
      "col.ui.v1.RPWidgetR\005child\022\024\n\005width\030\002 \001(\002" +
      "R\005width\0229\n\005color\030\003 \001(\0132#.proto.renderpro" +
      "tocol.ui.v1.RPColorR\005color\022\033\n\006radius\030\004 \001" +
      "(\002H\000R\006radius\210\001\001B\t\n\007_radius\"\277\001\n\006RPClip\022:\n" +
      "\005child\030\001 \001(\0132$.proto.renderprotocol.ui.v" +
      "1.RPWidgetR\005child\022=\n\005shape\030\002 \001(\0132\'.proto" +
      ".renderprotocol.ui.v1.RPClipShapeR\005shape" +
      "\022:\n\004type\030\003 \001(\0162&.proto.renderprotocol.ui" +
      ".v1.RPClipTypeR\004type\"]\n\tRPOpacity\022:\n\005chi" +
      "ld\030\001 \001(\0132$.proto.renderprotocol.ui.v1.RP" +
      "WidgetR\005child\022\024\n\005value\030\002 \001(\002R\005value\"d\n\014R" +
      "PVisibility\022:\n\005child\030\001 \001(\0132$.proto.rende" +
      "rprotocol.ui.v1.RPWidgetR\005child\022\030\n\007visib" +
      "le\030\002 \001(\010R\007visible\"\317\001\n\010RPShadow\022:\n\005child\030" +
      "\001 \001(\0132$.proto.renderprotocol.ui.v1.RPWid" +
      "getR\005child\0229\n\005color\030\002 \001(\0132#.proto.render" +
      "protocol.ui.v1.RPColorR\005color\022\026\n\006radius\030" +
      "\003 \001(\002R\006radius\022\031\n\010offset_x\030\004 \001(\002R\007offsetX" +
      "\022\031\n\010offset_y\030\005 \001(\002R\007offsetY\"\332\002\n\tRPSizeBo" +
      "x\022:\n\005child\030\001 \001(\0132$.proto.renderprotocol." +
      "ui.v1.RPWidgetR\005child\022\031\n\005width\030\002 \001(\002H\000R\005" +
      "width\210\001\001\022\033\n\006height\030\003 \001(\002H\001R\006height\210\001\001\022 \n" +
      "\tmin_width\030\004 \001(\002H\002R\010minWidth\210\001\001\022\"\n\nmin_h" +
      "eight\030\005 \001(\002H\003R\tminHeight\210\001\001\022 \n\tmax_width" +
      "\030\006 \001(\002H\004R\010maxWidth\210\001\001\022\"\n\nmax_height\030\007 \001(" +
      "\002H\005R\tmaxHeight\210\001\001B\010\n\006_widthB\t\n\007_heightB\014" +
      "\n\n_min_widthB\r\n\013_min_heightB\014\n\n_max_widt" +
      "hB\r\n\013_max_height\"\250\001\n\nRPSafeArea\022:\n\005child" +
      "\030\001 \001(\0132$.proto.renderprotocol.ui.v1.RPWi" +
      "dgetR\005child\022\020\n\003top\030\002 \001(\010R\003top\022\026\n\006bottom\030" +
      "\003 \001(\010R\006bottom\022\030\n\007leading\030\004 \001(\010R\007leading\022" +
      "\032\n\010trailing\030\005 \001(\010R\010trailing\"\257\001\n\rRPAspect" +
      "Ratio\022:\n\005child\030\001 \001(\0132$.proto.renderproto" +
      "col.ui.v1.RPWidgetR\005child\022\024\n\005ratio\030\002 \001(\002" +
      "R\005ratio\022L\n\014content_mode\030\003 \001(\0162).proto.re" +
      "nderprotocol.ui.v1.RPContentModeR\013conten" +
      "tMode\"\352\001\n\014RPPositioned\022:\n\005child\030\001 \001(\0132$." +
      "proto.renderprotocol.ui.v1.RPWidgetR\005chi" +
      "ld\022\025\n\003top\030\002 \001(\002H\000R\003top\210\001\001\022\033\n\006bottom\030\003 \001(" +
      "\002H\001R\006bottom\210\001\001\022\035\n\007leading\030\004 \001(\002H\002R\007leadi" +
      "ng\210\001\001\022\037\n\010trailing\030\005 \001(\002H\003R\010trailing\210\001\001B\006" +
      "\n\004_topB\t\n\007_bottomB\n\n\010_leadingB\013\n\t_traili" +
      "ng\"\341\001\n\010RPButton\022:\n\005label\030\001 \001(\0132$.proto.r" +
      "enderprotocol.ui.v1.RPWidgetR\005label\022<\n\006a" +
      "ction\030\002 \001(\0132$.proto.renderprotocol.ui.v1" +
      ".RPActionR\006action\022?\n\005style\030\003 \001(\0162).proto" +
      ".renderprotocol.ui.v1.RPButtonStyleR\005sty" +
      "le\022\032\n\010disabled\030\004 \001(\010R\010disabled\"\327\002\n\010RPTog" +
      "gle\022\031\n\010field_id\030\001 \001(\tR\007fieldId\022#\n\rinitia" +
      "l_value\030\002 \001(\010R\014initialValue\022?\n\005label\030\003 \001" +
      "(\0132$.proto.renderprotocol.ui.v1.RPWidget" +
      "H\000R\005label\210\001\001\022C\n\010on_color\030\004 \001(\0132#.proto.r" +
      "enderprotocol.ui.v1.RPColorH\001R\007onColor\210\001" +
      "\001\022\030\n\007enabled\030\005 \001(\010R\007enabled\022F\n\ton_change" +
      "\030\006 \001(\0132$.proto.renderprotocol.ui.v1.RPAc" +
      "tionH\002R\010onChange\210\001\001B\010\n\006_labelB\013\n\t_on_col" +
      "orB\014\n\n_on_change\"\360\002\n\006RPCard\022:\n\005child\030\001 \001" +
      "(\0132$.proto.renderprotocol.ui.v1.RPWidget" +
      "R\005child\022!\n\televation\030\002 \001(\002H\000R\televation\210" +
      "\001\001\022(\n\rcorner_radius\030\003 \001(\002H\001R\014cornerRadiu" +
      "s\210\001\001\022S\n\020background_color\030\004 \001(\0132#.proto.r" +
      "enderprotocol.ui.v1.RPColorH\002R\017backgroun" +
      "dColor\210\001\001\022G\n\007padding\030\005 \001(\0132(.proto.rende" +
      "rprotocol.ui.v1.RPEdgeInsetsH\003R\007padding\210" +
      "\001\001B\014\n\n_elevationB\020\n\016_corner_radiusB\023\n\021_b" +
      "ackground_colorB\n\n\010_padding\"\216\003\n\nRPListTi" +
      "le\022C\n\007leading\030\001 \001(\0132$.proto.renderprotoc" +
      "ol.ui.v1.RPWidgetH\000R\007leading\210\001\001\022:\n\005title" +
      "\030\002 \001(\0132$.proto.renderprotocol.ui.v1.RPWi" +
      "dgetR\005title\022E\n\010subtitle\030\003 \001(\0132$.proto.re" +
      "nderprotocol.ui.v1.RPWidgetH\001R\010subtitle\210" +
      "\001\001\022E\n\010trailing\030\004 \001(\0132$.proto.renderproto" +
      "col.ui.v1.RPWidgetH\002R\010trailing\210\001\001\022@\n\006on_" +
      "tap\030\005 \001(\0132$.proto.renderprotocol.ui.v1.R" +
      "PActionH\003R\005onTap\210\001\001B\n\n\010_leadingB\013\n\t_subt" +
      "itleB\013\n\t_trailingB\t\n\007_on_tap\"\320\002\n\010RPAppBa" +
      "r\022?\n\005title\030\001 \001(\0132$.proto.renderprotocol." +
      "ui.v1.RPWidgetH\000R\005title\210\001\001\022C\n\007leading\030\002 " +
      "\001(\0132$.proto.renderprotocol.ui.v1.RPWidge" +
      "tH\001R\007leading\210\001\001\022>\n\007actions\030\003 \003(\0132$.proto" +
      ".renderprotocol.ui.v1.RPWidgetR\007actions\022" +
      "S\n\020background_color\030\004 \001(\0132#.proto.render" +
      "protocol.ui.v1.RPColorH\002R\017backgroundColo" +
      "r\210\001\001B\010\n\006_titleB\n\n\010_leadingB\023\n\021_backgroun" +
      "d_color\"\264\001\n\007RPBadge\022:\n\005child\030\001 \001(\0132$.pro" +
      "to.renderprotocol.ui.v1.RPWidgetR\005child\022" +
      "\031\n\005value\030\002 \001(\tH\000R\005value\210\001\001\022>\n\005color\030\003 \001(" +
      "\0132#.proto.renderprotocol.ui.v1.RPColorH\001" +
      "R\005color\210\001\001B\010\n\006_valueB\010\n\006_color\"\352\002\n\nRPSca" +
      "ffold\022B\n\007app_bar\030\001 \001(\0132$.proto.renderpro" +
      "tocol.ui.v1.RPAppBarH\000R\006appBar\210\001\001\0228\n\004bod" +
      "y\030\002 \001(\0132$.proto.renderprotocol.ui.v1.RPW" +
      "idgetR\004body\022U\n\016bottom_nav_bar\030\003 \001(\0132*.pr" +
      "oto.renderprotocol.ui.v1.RPBottomNavBarH" +
      "\001R\014bottomNavBar\210\001\001\022S\n\020background_color\030\004" +
      " \001(\0132#.proto.renderprotocol.ui.v1.RPColo" +
      "rH\002R\017backgroundColor\210\001\001B\n\n\010_app_barB\021\n\017_" +
      "bottom_nav_barB\023\n\021_background_color\"\336\002\n\021" +
      "RPGestureDetector\022:\n\005child\030\001 \001(\0132$.proto" +
      ".renderprotocol.ui.v1.RPWidgetR\005child\022@\n" +
      "\006on_tap\030\002 \001(\0132$.proto.renderprotocol.ui." +
      "v1.RPActionH\000R\005onTap\210\001\001\022M\n\ron_long_press" +
      "\030\003 \001(\0132$.proto.renderprotocol.ui.v1.RPAc" +
      "tionH\001R\013onLongPress\210\001\001\022M\n\ron_double_tap\030" +
      "\004 \001(\0132$.proto.renderprotocol.ui.v1.RPAct" +
      "ionH\002R\013onDoubleTap\210\001\001B\t\n\007_on_tapB\020\n\016_on_" +
      "long_pressB\020\n\016_on_double_tapB\303\001\n\037com.nuk" +
      "ive.renderprotocol.ui.v1B\rRpUiCoreProtoH" +
      "\001P\001\370\001\001\242\002\003PRU\252\002\032Proto.Renderprotocol.Ui.V" +
      "1\272\002\000\312\002\032Proto\\Renderprotocol\\Ui\\V1\342\002&Prot" +
      "o\\Renderprotocol\\Ui\\V1\\GPBMetadata\352\002\035Pro" +
      "to::Renderprotocol::Ui::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.nukive.renderprotocol.ui.v1.RpUiActionProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiColorProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiDividerProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiIconProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiImageProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiProgressIndicatorProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiSliderProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiSpacerProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiTextProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiTextFieldProto.getDescriptor(),
        });
    internal_static_proto_renderprotocol_ui_v1_RPWidget_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_proto_renderprotocol_ui_v1_RPWidget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPWidget_descriptor,
        new java.lang.String[] { "Id", "Row", "Column", "Stack", "Scrollable", "LazyList", "LazyGrid", "Wrap", "Center", "Expanded", "Padding", "Background", "Border", "Clip", "Opacity", "Visibility", "Shadow", "SizeBox", "SafeArea", "AspectRatio", "Positioned", "Text", "Image", "Icon", "Spacer", "Divider", "ProgressIndicator", "Button", "TextField", "Toggle", "Slider", "Card", "ListTile", "AppBar", "BottomNavBar", "Badge", "Scaffold", "GestureDetector", "Content", });
    internal_static_proto_renderprotocol_ui_v1_RPRow_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_proto_renderprotocol_ui_v1_RPRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPRow_descriptor,
        new java.lang.String[] { "Children", "Spacing", "Alignment", });
    internal_static_proto_renderprotocol_ui_v1_RPColumn_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_proto_renderprotocol_ui_v1_RPColumn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPColumn_descriptor,
        new java.lang.String[] { "Children", "Spacing", "Alignment", });
    internal_static_proto_renderprotocol_ui_v1_RPStack_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_proto_renderprotocol_ui_v1_RPStack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPStack_descriptor,
        new java.lang.String[] { "Children", "Alignment", });
    internal_static_proto_renderprotocol_ui_v1_RPScrollable_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_proto_renderprotocol_ui_v1_RPScrollable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPScrollable_descriptor,
        new java.lang.String[] { "Child", "Axis", "ShowsIndicators", });
    internal_static_proto_renderprotocol_ui_v1_RPLazyList_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_proto_renderprotocol_ui_v1_RPLazyList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPLazyList_descriptor,
        new java.lang.String[] { "Children", "Axis", "Spacing", "ShowsIndicators", "Separator", });
    internal_static_proto_renderprotocol_ui_v1_RPLazyGrid_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_proto_renderprotocol_ui_v1_RPLazyGrid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPLazyGrid_descriptor,
        new java.lang.String[] { "Children", "Layout", "Spacing", "RunSpacing", });
    internal_static_proto_renderprotocol_ui_v1_RPWrap_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_proto_renderprotocol_ui_v1_RPWrap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPWrap_descriptor,
        new java.lang.String[] { "Children", "Spacing", "RunSpacing", "Alignment", });
    internal_static_proto_renderprotocol_ui_v1_RPCenter_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_proto_renderprotocol_ui_v1_RPCenter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPCenter_descriptor,
        new java.lang.String[] { "Child", });
    internal_static_proto_renderprotocol_ui_v1_RPExpanded_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_proto_renderprotocol_ui_v1_RPExpanded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPExpanded_descriptor,
        new java.lang.String[] { "Child", "Flex", });
    internal_static_proto_renderprotocol_ui_v1_RPPadding_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_proto_renderprotocol_ui_v1_RPPadding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPPadding_descriptor,
        new java.lang.String[] { "Child", "All", "Symmetric", "Explicit", "Value", });
    internal_static_proto_renderprotocol_ui_v1_RPBackground_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_proto_renderprotocol_ui_v1_RPBackground_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPBackground_descriptor,
        new java.lang.String[] { "Child", "Color", });
    internal_static_proto_renderprotocol_ui_v1_RPBorder_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_proto_renderprotocol_ui_v1_RPBorder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPBorder_descriptor,
        new java.lang.String[] { "Child", "Width", "Color", "Radius", });
    internal_static_proto_renderprotocol_ui_v1_RPClip_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_proto_renderprotocol_ui_v1_RPClip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPClip_descriptor,
        new java.lang.String[] { "Child", "Shape", "Type", });
    internal_static_proto_renderprotocol_ui_v1_RPOpacity_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_proto_renderprotocol_ui_v1_RPOpacity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPOpacity_descriptor,
        new java.lang.String[] { "Child", "Value", });
    internal_static_proto_renderprotocol_ui_v1_RPVisibility_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_proto_renderprotocol_ui_v1_RPVisibility_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPVisibility_descriptor,
        new java.lang.String[] { "Child", "Visible", });
    internal_static_proto_renderprotocol_ui_v1_RPShadow_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_proto_renderprotocol_ui_v1_RPShadow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPShadow_descriptor,
        new java.lang.String[] { "Child", "Color", "Radius", "OffsetX", "OffsetY", });
    internal_static_proto_renderprotocol_ui_v1_RPSizeBox_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_proto_renderprotocol_ui_v1_RPSizeBox_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPSizeBox_descriptor,
        new java.lang.String[] { "Child", "Width", "Height", "MinWidth", "MinHeight", "MaxWidth", "MaxHeight", });
    internal_static_proto_renderprotocol_ui_v1_RPSafeArea_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_proto_renderprotocol_ui_v1_RPSafeArea_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPSafeArea_descriptor,
        new java.lang.String[] { "Child", "Top", "Bottom", "Leading", "Trailing", });
    internal_static_proto_renderprotocol_ui_v1_RPAspectRatio_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_proto_renderprotocol_ui_v1_RPAspectRatio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPAspectRatio_descriptor,
        new java.lang.String[] { "Child", "Ratio", "ContentMode", });
    internal_static_proto_renderprotocol_ui_v1_RPPositioned_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_proto_renderprotocol_ui_v1_RPPositioned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPPositioned_descriptor,
        new java.lang.String[] { "Child", "Top", "Bottom", "Leading", "Trailing", });
    internal_static_proto_renderprotocol_ui_v1_RPButton_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_proto_renderprotocol_ui_v1_RPButton_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPButton_descriptor,
        new java.lang.String[] { "Label", "Action", "Style", "Disabled", });
    internal_static_proto_renderprotocol_ui_v1_RPToggle_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_proto_renderprotocol_ui_v1_RPToggle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPToggle_descriptor,
        new java.lang.String[] { "FieldId", "InitialValue", "Label", "OnColor", "Enabled", "OnChange", });
    internal_static_proto_renderprotocol_ui_v1_RPCard_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_proto_renderprotocol_ui_v1_RPCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPCard_descriptor,
        new java.lang.String[] { "Child", "Elevation", "CornerRadius", "BackgroundColor", "Padding", });
    internal_static_proto_renderprotocol_ui_v1_RPListTile_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_proto_renderprotocol_ui_v1_RPListTile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPListTile_descriptor,
        new java.lang.String[] { "Leading", "Title", "Subtitle", "Trailing", "OnTap", });
    internal_static_proto_renderprotocol_ui_v1_RPAppBar_descriptor =
      getDescriptor().getMessageType(25);
    internal_static_proto_renderprotocol_ui_v1_RPAppBar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPAppBar_descriptor,
        new java.lang.String[] { "Title", "Leading", "Actions", "BackgroundColor", });
    internal_static_proto_renderprotocol_ui_v1_RPBadge_descriptor =
      getDescriptor().getMessageType(26);
    internal_static_proto_renderprotocol_ui_v1_RPBadge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPBadge_descriptor,
        new java.lang.String[] { "Child", "Value", "Color", });
    internal_static_proto_renderprotocol_ui_v1_RPScaffold_descriptor =
      getDescriptor().getMessageType(27);
    internal_static_proto_renderprotocol_ui_v1_RPScaffold_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPScaffold_descriptor,
        new java.lang.String[] { "AppBar", "Body", "BottomNavBar", "BackgroundColor", });
    internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_descriptor =
      getDescriptor().getMessageType(28);
    internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPGestureDetector_descriptor,
        new java.lang.String[] { "Child", "OnTap", "OnLongPress", "OnDoubleTap", });
    descriptor.resolveAllFeaturesImmutable();
    com.nukive.renderprotocol.ui.v1.RpUiActionProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiBottomNavBarProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiColorProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiCoreSupportProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiDividerProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiIconProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiImageProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiProgressIndicatorProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiSliderProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiSpacerProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiTextProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiTextFieldProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
