// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_action.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.ui.v1;

@com.google.protobuf.Generated
public final class RpUiActionProto extends com.google.protobuf.GeneratedFile {
  private RpUiActionProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RpUiActionProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPOpenUrlAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPOpenUrlAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPDismissAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPDismissAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPCustomAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPCustomAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_ui_v1_RPCustomAction_PayloadEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_ui_v1_RPCustomAction_PayloadEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-proto/renderprotocol/ui/v1/rp_ui_actio" +
      "n.proto\022\032proto.renderprotocol.ui.v1\"\211\003\n\010" +
      "RPAction\022P\n\nnavigation\030\001 \001(\0132..proto.ren" +
      "derprotocol.ui.v1.RPNavigationActionH\000R\n" +
      "navigation\022H\n\010api_call\030\002 \001(\0132+.proto.ren" +
      "derprotocol.ui.v1.RPApiCallActionH\000R\007api" +
      "Call\022H\n\010open_url\030\003 \001(\0132+.proto.renderpro" +
      "tocol.ui.v1.RPOpenUrlActionH\000R\007openUrl\022G" +
      "\n\007dismiss\030\004 \001(\0132+.proto.renderprotocol.u" +
      "i.v1.RPDismissActionH\000R\007dismiss\022D\n\006custo" +
      "m\030\005 \001(\0132*.proto.renderprotocol.ui.v1.RPC" +
      "ustomActionH\000R\006customB\010\n\006action\"\343\001\n\022RPNa" +
      "vigationAction\022.\n\023destination_view_id\030\001 " +
      "\001(\tR\021destinationViewId\022^\n\nparameters\030\002 \003" +
      "(\0132>.proto.renderprotocol.ui.v1.RPNaviga" +
      "tionAction.ParametersEntryR\nparameters\032=" +
      "\n\017ParametersEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005v" +
      "alue\030\002 \001(\tR\005value:\0028\001\"\367\001\n\017RPApiCallActio" +
      "n\022\032\n\010endpoint\030\001 \001(\tR\010endpoint\022\026\n\006method\030" +
      "\002 \001(\tR\006method\022R\n\007headers\030\003 \003(\01328.proto.r" +
      "enderprotocol.ui.v1.RPApiCallAction.Head" +
      "ersEntryR\007headers\022\027\n\004body\030\004 \001(\tH\000R\004body\210" +
      "\001\001\032:\n\014HeadersEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005" +
      "value\030\002 \001(\tR\005value:\0028\001B\007\n\005_body\"?\n\017RPOpe" +
      "nUrlAction\022\020\n\003url\030\001 \001(\tR\003url\022\032\n\010external" +
      "\030\002 \001(\010R\010external\"\021\n\017RPDismissAction\"\300\001\n\016" +
      "RPCustomAction\022\037\n\013action_type\030\001 \001(\tR\nact" +
      "ionType\022Q\n\007payload\030\002 \003(\01327.proto.renderp" +
      "rotocol.ui.v1.RPCustomAction.PayloadEntr" +
      "yR\007payload\032:\n\014PayloadEntry\022\020\n\003key\030\001 \001(\tR" +
      "\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001B\305\001\n\037com.n" +
      "ukive.renderprotocol.ui.v1B\017RpUiActionPr" +
      "otoH\001P\001\370\001\001\242\002\003PRU\252\002\032Proto.Renderprotocol." +
      "Ui.V1\272\002\000\312\002\032Proto\\Renderprotocol\\Ui\\V1\342\002&" +
      "Proto\\Renderprotocol\\Ui\\V1\\GPBMetadata\352\002" +
      "\035Proto::Renderprotocol::Ui::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_renderprotocol_ui_v1_RPAction_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_proto_renderprotocol_ui_v1_RPAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPAction_descriptor,
        new java.lang.String[] { "Navigation", "ApiCall", "OpenUrl", "Dismiss", "Custom", "Action", });
    internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_descriptor,
        new java.lang.String[] { "DestinationViewId", "Parameters", });
    internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_ParametersEntry_descriptor =
      internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_descriptor.getNestedType(0);
    internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPNavigationAction_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_descriptor,
        new java.lang.String[] { "Endpoint", "Method", "Headers", "Body", });
    internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_HeadersEntry_descriptor =
      internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_descriptor.getNestedType(0);
    internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPApiCallAction_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_renderprotocol_ui_v1_RPOpenUrlAction_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_proto_renderprotocol_ui_v1_RPOpenUrlAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPOpenUrlAction_descriptor,
        new java.lang.String[] { "Url", "External", });
    internal_static_proto_renderprotocol_ui_v1_RPDismissAction_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_proto_renderprotocol_ui_v1_RPDismissAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPDismissAction_descriptor,
        new java.lang.String[] { });
    internal_static_proto_renderprotocol_ui_v1_RPCustomAction_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_proto_renderprotocol_ui_v1_RPCustomAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPCustomAction_descriptor,
        new java.lang.String[] { "ActionType", "Payload", });
    internal_static_proto_renderprotocol_ui_v1_RPCustomAction_PayloadEntry_descriptor =
      internal_static_proto_renderprotocol_ui_v1_RPCustomAction_descriptor.getNestedType(0);
    internal_static_proto_renderprotocol_ui_v1_RPCustomAction_PayloadEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_ui_v1_RPCustomAction_PayloadEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
