// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_metadata.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.api.v1;

@com.google.protobuf.Generated
public interface RPAppMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.renderprotocol.api.v1.RPAppMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bundle_id = 1 [json_name = "bundleId"];</code>
   * @return The bundleId.
   */
  java.lang.String getBundleId();
  /**
   * <code>string bundle_id = 1 [json_name = "bundleId"];</code>
   * @return The bytes for bundleId.
   */
  com.google.protobuf.ByteString
      getBundleIdBytes();

  /**
   * <code>string app_version = 2 [json_name = "appVersion"];</code>
   * @return The appVersion.
   */
  java.lang.String getAppVersion();
  /**
   * <code>string app_version = 2 [json_name = "appVersion"];</code>
   * @return The bytes for appVersion.
   */
  com.google.protobuf.ByteString
      getAppVersionBytes();

  /**
   * <code>.proto.renderprotocol.api.v1.RPPlatform platform = 3 [json_name = "platform"];</code>
   * @return The enum numeric value on the wire for platform.
   */
  int getPlatformValue();
  /**
   * <code>.proto.renderprotocol.api.v1.RPPlatform platform = 3 [json_name = "platform"];</code>
   * @return The platform.
   */
  com.nukive.renderprotocol.api.v1.RPPlatform getPlatform();

  /**
   * <code>string locale = 4 [json_name = "locale"];</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <code>string locale = 4 [json_name = "locale"];</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();

  /**
   * <code>string sdk_version = 5 [json_name = "sdkVersion"];</code>
   * @return The sdkVersion.
   */
  java.lang.String getSdkVersion();
  /**
   * <code>string sdk_version = 5 [json_name = "sdkVersion"];</code>
   * @return The bytes for sdkVersion.
   */
  com.google.protobuf.ByteString
      getSdkVersionBytes();
}
