// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_render_service.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.api.v1;

@com.google.protobuf.Generated
public final class RpApiRenderServiceProto extends com.google.protobuf.GeneratedFile {
  private RpApiRenderServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RpApiRenderServiceProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPFetchComponentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7proto/renderprotocol/api/v1/rp_api_ren" +
      "der_service.proto\022\033proto.renderprotocol." +
      "api.v1\0321proto/renderprotocol/api/v1/rp_a" +
      "pi_metadata.proto\032/proto/renderprotocol/" +
      "api/v1/rp_api_status.proto\032+proto/render" +
      "protocol/ui/v1/rp_ui_core.proto\"\330\002\n\030RPFe" +
      "tchRenderTreeRequest\022G\n\007context\030\001 \001(\0132-." +
      "proto.renderprotocol.api.v1.RPSessionCon" +
      "textR\007context\022\016\n\002id\030\002 \001(\tR\002id\022e\n\nparamet" +
      "ers\030\003 \003(\0132E.proto.renderprotocol.api.v1." +
      "RPFetchRenderTreeRequest.ParametersEntry" +
      "R\nparameters\022*\n\016cached_version\030\004 \001(\tH\000R\r" +
      "cachedVersion\210\001\001\032=\n\017ParametersEntry\022\020\n\003k" +
      "ey\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001B" +
      "\021\n\017_cached_version\"\341\001\n\031RPFetchRenderTree" +
      "Response\022=\n\006status\030\001 \001(\0132%.proto.renderp" +
      "rotocol.api.v1.RPStatusR\006status\022\016\n\002id\030\002 " +
      "\001(\tR\002id\0228\n\004tree\030\003 \001(\0132$.proto.renderprot" +
      "ocol.ui.v1.RPWidgetR\004tree\022\030\n\007version\030\004 \001" +
      "(\tR\007version\022!\n\014not_modified\030\005 \001(\010R\013notMo" +
      "dified\"\303\002\n\027RPFetchComponentRequest\022G\n\007co" +
      "ntext\030\001 \001(\0132-.proto.renderprotocol.api.v" +
      "1.RPSessionContextR\007context\022\027\n\007tree_id\030\002" +
      " \001(\tR\006treeId\022!\n\014component_id\030\003 \001(\tR\013comp" +
      "onentId\022d\n\nparameters\030\004 \003(\0132D.proto.rend" +
      "erprotocol.api.v1.RPFetchComponentReques" +
      "t.ParametersEntryR\nparameters\032=\n\017Paramet" +
      "ersEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(" +
      "\tR\005value:\0028\001\"\267\001\n\030RPFetchComponentRespons" +
      "e\022=\n\006status\030\001 \001(\0132%.proto.renderprotocol" +
      ".api.v1.RPStatusR\006status\022B\n\tcomponent\030\002 " +
      "\001(\0132$.proto.renderprotocol.ui.v1.RPWidge" +
      "tR\tcomponent\022\030\n\007version\030\003 \001(\tR\007version\"\241" +
      "\002\n\034RPSubscribeRenderTreeRequest\022G\n\007conte" +
      "xt\030\001 \001(\0132-.proto.renderprotocol.api.v1.R" +
      "PSessionContextR\007context\022\016\n\002id\030\002 \001(\tR\002id" +
      "\022i\n\nparameters\030\003 \003(\0132I.proto.renderproto" +
      "col.api.v1.RPSubscribeRenderTreeRequest." +
      "ParametersEntryR\nparameters\032=\n\017Parameter" +
      "sEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR" +
      "\005value:\0028\001\"\230\002\n\035RPSubscribeRenderTreeResp" +
      "onse\022=\n\006status\030\001 \001(\0132%.proto.renderproto" +
      "col.api.v1.RPStatusR\006status\022\016\n\002id\030\002 \001(\tR" +
      "\002id\022T\n\013update_type\030\003 \001(\01623.proto.renderp" +
      "rotocol.api.v1.RPRenderTreeUpdateTypeR\nu" +
      "pdateType\0228\n\004tree\030\004 \001(\0132$.proto.renderpr" +
      "otocol.ui.v1.RPWidgetR\004tree\022\030\n\007version\030\005" +
      " \001(\tR\007version*\231\001\n\026RPRenderTreeUpdateType" +
      "\022*\n&RP_RENDER_TREE_UPDATE_TYPE_UNSPECIFI" +
      "ED\020\000\022+\n\'RP_RENDER_TREE_UPDATE_TYPE_FULL_" +
      "REPLACE\020\001\022&\n\"RP_RENDER_TREE_UPDATE_TYPE_" +
      "PARTIAL\020\0022\252\003\n\017RPRenderService\022\202\001\n\021RPFetc" +
      "hRenderTree\0225.proto.renderprotocol.api.v" +
      "1.RPFetchRenderTreeRequest\0326.proto.rende" +
      "rprotocol.api.v1.RPFetchRenderTreeRespon" +
      "se\022\177\n\020RPFetchComponent\0224.proto.renderpro" +
      "tocol.api.v1.RPFetchComponentRequest\0325.p" +
      "roto.renderprotocol.api.v1.RPFetchCompon" +
      "entResponse\022\220\001\n\025RPSubscribeRenderTree\0229." +
      "proto.renderprotocol.api.v1.RPSubscribeR" +
      "enderTreeRequest\032:.proto.renderprotocol." +
      "api.v1.RPSubscribeRenderTreeResponse0\001B\322" +
      "\001\n com.nukive.renderprotocol.api.v1B\027RpA" +
      "piRenderServiceProtoH\001P\001\370\001\001\242\002\003PRA\252\002\033Prot" +
      "o.Renderprotocol.Api.V1\272\002\000\312\002\033Proto\\Rende" +
      "rprotocol\\Api\\V1\342\002\'Proto\\Renderprotocol\\" +
      "Api\\V1\\GPBMetadata\352\002\036Proto::Renderprotoc" +
      "ol::Api::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.nukive.renderprotocol.api.v1.RpApiMetadataProto.getDescriptor(),
          com.nukive.renderprotocol.api.v1.RpApiStatusProto.getDescriptor(),
          com.nukive.renderprotocol.ui.v1.RpUiCoreProto.getDescriptor(),
        });
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_descriptor,
        new java.lang.String[] { "Context", "Id", "Parameters", "CachedVersion", });
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_ParametersEntry_descriptor =
      internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_descriptor.getNestedType(0);
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeResponse_descriptor,
        new java.lang.String[] { "Status", "Id", "Tree", "Version", "NotModified", });
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_descriptor,
        new java.lang.String[] { "Context", "TreeId", "ComponentId", "Parameters", });
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_ParametersEntry_descriptor =
      internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_descriptor.getNestedType(0);
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPFetchComponentRequest_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_proto_renderprotocol_api_v1_RPFetchComponentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPFetchComponentResponse_descriptor,
        new java.lang.String[] { "Status", "Component", "Version", });
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_descriptor,
        new java.lang.String[] { "Context", "Id", "Parameters", });
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_ParametersEntry_descriptor =
      internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_descriptor.getNestedType(0);
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeRequest_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_renderprotocol_api_v1_RPSubscribeRenderTreeResponse_descriptor,
        new java.lang.String[] { "Status", "Id", "UpdateType", "Tree", "Version", });
    descriptor.resolveAllFeaturesImmutable();
    com.nukive.renderprotocol.api.v1.RpApiMetadataProto.getDescriptor();
    com.nukive.renderprotocol.api.v1.RpApiStatusProto.getDescriptor();
    com.nukive.renderprotocol.ui.v1.RpUiCoreProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
