// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_event_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.api.v1;

@kotlin.jvm.JvmName("-initializerPCustomEventPayload")
public inline fun rPCustomEventPayload(block: com.nukive.renderprotocol.api.v1.RPCustomEventPayloadKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.api.v1.RPCustomEventPayload =
  com.nukive.renderprotocol.api.v1.RPCustomEventPayloadKt.Dsl._create(com.nukive.renderprotocol.api.v1.RPCustomEventPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.api.v1.RPCustomEventPayload`
 */
public object RPCustomEventPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.api.v1.RPCustomEventPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.api.v1.RPCustomEventPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.api.v1.RPCustomEventPayload = _builder.build()

    /**
     * `string event_name = 1 [json_name = "eventName"];`
     */
    public var eventName: kotlin.String
      @kotlin.jvm.JvmName("getEventName")
        get() = _builder.eventName
      @kotlin.jvm.JvmName("setEventName")
        set(value) {
        _builder.eventName = value
      }
    /**
     * `string event_name = 1 [json_name = "eventName"];`
     */
    public fun clearEventName() {
      _builder.clearEventName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PropertiesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> properties = 2 [json_name = "properties"];`
     */
     public val properties: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, PropertiesProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getPropertiesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.propertiesMap
      )
    /**
     * `map<string, string> properties = 2 [json_name = "properties"];`
     */
    @kotlin.jvm.JvmName("putProperties")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, PropertiesProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putProperties(key, value)
       }
    /**
     * `map<string, string> properties = 2 [json_name = "properties"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setProperties")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, PropertiesProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> properties = 2 [json_name = "properties"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeProperties")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, PropertiesProxy>
      .remove(key: kotlin.String) {
         _builder.removeProperties(key)
       }
    /**
     * `map<string, string> properties = 2 [json_name = "properties"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllProperties")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, PropertiesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllProperties(map)
       }
    /**
     * `map<string, string> properties = 2 [json_name = "properties"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearProperties")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, PropertiesProxy>
      .clear() {
         _builder.clearProperties()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.api.v1.RPCustomEventPayload.copy(block: `com.nukive.renderprotocol.api.v1`.RPCustomEventPayloadKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.api.v1.RPCustomEventPayload =
  `com.nukive.renderprotocol.api.v1`.RPCustomEventPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

