// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_handshake_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.api.v1;

@kotlin.jvm.JvmName("-initializerPEndSessionResponse")
public inline fun rPEndSessionResponse(block: com.nukive.renderprotocol.api.v1.RPEndSessionResponseKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.api.v1.RPEndSessionResponse =
  com.nukive.renderprotocol.api.v1.RPEndSessionResponseKt.Dsl._create(com.nukive.renderprotocol.api.v1.RPEndSessionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.api.v1.RPEndSessionResponse`
 */
public object RPEndSessionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.api.v1.RPEndSessionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.api.v1.RPEndSessionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.api.v1.RPEndSessionResponse = _builder.build()

    /**
     * `.proto.renderprotocol.api.v1.RPStatus status = 1 [json_name = "status"];`
     */
    public var status: com.nukive.renderprotocol.api.v1.RPStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * `.proto.renderprotocol.api.v1.RPStatus status = 1 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * `.proto.renderprotocol.api.v1.RPStatus status = 1 [json_name = "status"];`
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    public val RPEndSessionResponseKt.Dsl.statusOrNull: com.nukive.renderprotocol.api.v1.RPStatus?
      get() = _builder.statusOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.api.v1.RPEndSessionResponse.copy(block: `com.nukive.renderprotocol.api.v1`.RPEndSessionResponseKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.api.v1.RPEndSessionResponse =
  `com.nukive.renderprotocol.api.v1`.RPEndSessionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.nukive.renderprotocol.api.v1.RPEndSessionResponseOrBuilder.statusOrNull: com.nukive.renderprotocol.api.v1.RPStatus?
  get() = if (hasStatus()) getStatus() else null

