// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_render_service.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.api.v1;

@com.google.protobuf.Generated
public interface RPFetchComponentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.renderprotocol.api.v1.RPFetchComponentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.renderprotocol.api.v1.RPStatus status = 1 [json_name = "status"];</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.proto.renderprotocol.api.v1.RPStatus status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  com.nukive.renderprotocol.api.v1.RPStatus getStatus();
  /**
   * <code>.proto.renderprotocol.api.v1.RPStatus status = 1 [json_name = "status"];</code>
   */
  com.nukive.renderprotocol.api.v1.RPStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget component = 2 [json_name = "component"];</code>
   * @return Whether the component field is set.
   */
  boolean hasComponent();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget component = 2 [json_name = "component"];</code>
   * @return The component.
   */
  com.nukive.renderprotocol.ui.v1.RPWidget getComponent();
  /**
   * <code>.proto.renderprotocol.ui.v1.RPWidget component = 2 [json_name = "component"];</code>
   */
  com.nukive.renderprotocol.ui.v1.RPWidgetOrBuilder getComponentOrBuilder();

  /**
   * <code>string version = 3 [json_name = "version"];</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
