// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_render_service.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.api.v1;

/**
 * Protobuf type {@code proto.renderprotocol.api.v1.RPFetchRenderTreeRequest}
 */
@com.google.protobuf.Generated
public final class RPFetchRenderTreeRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
    RPFetchRenderTreeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPFetchRenderTreeRequest");
  }
  // Use RPFetchRenderTreeRequest.newBuilder() to construct.
  private RPFetchRenderTreeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPFetchRenderTreeRequest() {
    id_ = "";
    cachedVersion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nukive.renderprotocol.api.v1.RpApiRenderServiceProto.internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nukive.renderprotocol.api.v1.RpApiRenderServiceProto.internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 3:
        return internalGetParameters();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nukive.renderprotocol.api.v1.RpApiRenderServiceProto.internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest.class, com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CONTEXT_FIELD_NUMBER = 1;
  private com.nukive.renderprotocol.api.v1.RPSessionContext context_;
  /**
   * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  @java.lang.Override
  public boolean hasContext() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  @java.lang.Override
  public com.nukive.renderprotocol.api.v1.RPSessionContext getContext() {
    return context_ == null ? com.nukive.renderprotocol.api.v1.RPSessionContext.getDefaultInstance() : context_;
  }
  /**
   * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
   */
  @java.lang.Override
  public com.nukive.renderprotocol.api.v1.RPSessionContextOrBuilder getContextOrBuilder() {
    return context_ == null ? com.nukive.renderprotocol.api.v1.RPSessionContext.getDefaultInstance() : context_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 2 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 2 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMETERS_FIELD_NUMBER = 3;
  private static final class ParametersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.nukive.renderprotocol.api.v1.RpApiRenderServiceProto.internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_ParametersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> parameters_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetParameters() {
    if (parameters_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ParametersDefaultEntryHolder.defaultEntry);
    }
    return parameters_;
  }
  public int getParametersCount() {
    return internalGetParameters().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
   */
  @java.lang.Override
  public boolean containsParameters(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetParameters().getMap().containsKey(key);
  }
  /**
   * Use {@link #getParametersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getParameters() {
    return getParametersMap();
  }
  /**
   * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getParametersMap() {
    return internalGetParameters().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getParametersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetParameters().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
   */
  @java.lang.Override
  public java.lang.String getParametersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetParameters().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CACHED_VERSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cachedVersion_ = "";
  /**
   * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
   * @return Whether the cachedVersion field is set.
   */
  @java.lang.Override
  public boolean hasCachedVersion() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
   * @return The cachedVersion.
   */
  @java.lang.Override
  public java.lang.String getCachedVersion() {
    java.lang.Object ref = cachedVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cachedVersion_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
   * @return The bytes for cachedVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCachedVersionBytes() {
    java.lang.Object ref = cachedVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cachedVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getContext());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, id_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetParameters(),
        ParametersDefaultEntryHolder.defaultEntry,
        3);
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, cachedVersion_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContext());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, id_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetParameters().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      parameters__ = ParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, parameters__);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, cachedVersion_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest)) {
      return super.equals(obj);
    }
    com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest other = (com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest) obj;

    if (hasContext() != other.hasContext()) return false;
    if (hasContext()) {
      if (!getContext()
          .equals(other.getContext())) return false;
    }
    if (!getId()
        .equals(other.getId())) return false;
    if (!internalGetParameters().equals(
        other.internalGetParameters())) return false;
    if (hasCachedVersion() != other.hasCachedVersion()) return false;
    if (hasCachedVersion()) {
      if (!getCachedVersion()
          .equals(other.getCachedVersion())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContext()) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (!internalGetParameters().getMap().isEmpty()) {
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetParameters().hashCode();
    }
    if (hasCachedVersion()) {
      hash = (37 * hash) + CACHED_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getCachedVersion().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.renderprotocol.api.v1.RPFetchRenderTreeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
      com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nukive.renderprotocol.api.v1.RpApiRenderServiceProto.internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetParameters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableParameters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nukive.renderprotocol.api.v1.RpApiRenderServiceProto.internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest.class, com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest.Builder.class);
    }

    // Construct using com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetContextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      id_ = "";
      internalGetMutableParameters().clear();
      cachedVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nukive.renderprotocol.api.v1.RpApiRenderServiceProto.internal_static_proto_renderprotocol_api_v1_RPFetchRenderTreeRequest_descriptor;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest getDefaultInstanceForType() {
      return com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest build() {
      com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest buildPartial() {
      com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest result = new com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.context_ = contextBuilder_ == null
            ? context_
            : contextBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.parameters_ = internalGetParameters();
        result.parameters_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cachedVersion_ = cachedVersion_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest) {
        return mergeFrom((com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest other) {
      if (other == com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest.getDefaultInstance()) return this;
      if (other.hasContext()) {
        mergeContext(other.getContext());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      internalGetMutableParameters().mergeFrom(
          other.internalGetParameters());
      bitField0_ |= 0x00000004;
      if (other.hasCachedVersion()) {
        cachedVersion_ = other.cachedVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetContextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              parameters__ = input.readMessage(
                  ParametersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableParameters().getMutableMap().put(
                  parameters__.getKey(), parameters__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              cachedVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.nukive.renderprotocol.api.v1.RPSessionContext context_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.api.v1.RPSessionContext, com.nukive.renderprotocol.api.v1.RPSessionContext.Builder, com.nukive.renderprotocol.api.v1.RPSessionContextOrBuilder> contextBuilder_;
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     * @return Whether the context field is set.
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     * @return The context.
     */
    public com.nukive.renderprotocol.api.v1.RPSessionContext getContext() {
      if (contextBuilder_ == null) {
        return context_ == null ? com.nukive.renderprotocol.api.v1.RPSessionContext.getDefaultInstance() : context_;
      } else {
        return contextBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     */
    public Builder setContext(com.nukive.renderprotocol.api.v1.RPSessionContext value) {
      if (contextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        context_ = value;
      } else {
        contextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     */
    public Builder setContext(
        com.nukive.renderprotocol.api.v1.RPSessionContext.Builder builderForValue) {
      if (contextBuilder_ == null) {
        context_ = builderForValue.build();
      } else {
        contextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     */
    public Builder mergeContext(com.nukive.renderprotocol.api.v1.RPSessionContext value) {
      if (contextBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          context_ != null &&
          context_ != com.nukive.renderprotocol.api.v1.RPSessionContext.getDefaultInstance()) {
          getContextBuilder().mergeFrom(value);
        } else {
          context_ = value;
        }
      } else {
        contextBuilder_.mergeFrom(value);
      }
      if (context_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     */
    public Builder clearContext() {
      bitField0_ = (bitField0_ & ~0x00000001);
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     */
    public com.nukive.renderprotocol.api.v1.RPSessionContext.Builder getContextBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     */
    public com.nukive.renderprotocol.api.v1.RPSessionContextOrBuilder getContextOrBuilder() {
      if (contextBuilder_ != null) {
        return contextBuilder_.getMessageOrBuilder();
      } else {
        return context_ == null ?
            com.nukive.renderprotocol.api.v1.RPSessionContext.getDefaultInstance() : context_;
      }
    }
    /**
     * <code>.proto.renderprotocol.api.v1.RPSessionContext context = 1 [json_name = "context"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nukive.renderprotocol.api.v1.RPSessionContext, com.nukive.renderprotocol.api.v1.RPSessionContext.Builder, com.nukive.renderprotocol.api.v1.RPSessionContextOrBuilder> 
        internalGetContextFieldBuilder() {
      if (contextBuilder_ == null) {
        contextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nukive.renderprotocol.api.v1.RPSessionContext, com.nukive.renderprotocol.api.v1.RPSessionContext.Builder, com.nukive.renderprotocol.api.v1.RPSessionContextOrBuilder>(
                getContext(),
                getParentForChildren(),
                isClean());
        context_ = null;
      }
      return contextBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 2 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 2 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 2 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> parameters_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetParameters() {
      if (parameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParametersDefaultEntryHolder.defaultEntry);
      }
      return parameters_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableParameters() {
      if (parameters_ == null) {
        parameters_ = com.google.protobuf.MapField.newMapField(
            ParametersDefaultEntryHolder.defaultEntry);
      }
      if (!parameters_.isMutable()) {
        parameters_ = parameters_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return parameters_;
    }
    public int getParametersCount() {
      return internalGetParameters().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
     */
    @java.lang.Override
    public boolean containsParameters(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetParameters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParametersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getParameters() {
      return getParametersMap();
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getParametersMap() {
      return internalGetParameters().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getParametersOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParameters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
     */
    @java.lang.Override
    public java.lang.String getParametersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParameters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearParameters() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableParameters().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
     */
    public Builder removeParameters(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableParameters().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableParameters() {
      bitField0_ |= 0x00000004;
      return internalGetMutableParameters().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
     */
    public Builder putParameters(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableParameters().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 3 [json_name = "parameters"];</code>
     */
    public Builder putAllParameters(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableParameters().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    private java.lang.Object cachedVersion_ = "";
    /**
     * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
     * @return Whether the cachedVersion field is set.
     */
    public boolean hasCachedVersion() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
     * @return The cachedVersion.
     */
    public java.lang.String getCachedVersion() {
      java.lang.Object ref = cachedVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cachedVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
     * @return The bytes for cachedVersion.
     */
    public com.google.protobuf.ByteString
        getCachedVersionBytes() {
      java.lang.Object ref = cachedVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cachedVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
     * @param value The cachedVersion to set.
     * @return This builder for chaining.
     */
    public Builder setCachedVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cachedVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCachedVersion() {
      cachedVersion_ = getDefaultInstance().getCachedVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string cached_version = 4 [json_name = "cachedVersion"];</code>
     * @param value The bytes for cachedVersion to set.
     * @return This builder for chaining.
     */
    public Builder setCachedVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cachedVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  private static final com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest();
  }

  public static com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPFetchRenderTreeRequest>
      PARSER = new com.google.protobuf.AbstractParser<RPFetchRenderTreeRequest>() {
    @java.lang.Override
    public RPFetchRenderTreeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPFetchRenderTreeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPFetchRenderTreeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nukive.renderprotocol.api.v1.RPFetchRenderTreeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

