// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_health_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.nukive.renderprotocol.api.v1;

@kotlin.jvm.JvmName("-initializerPHealthCheckRequest")
public inline fun rPHealthCheckRequest(block: com.nukive.renderprotocol.api.v1.RPHealthCheckRequestKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.api.v1.RPHealthCheckRequest =
  com.nukive.renderprotocol.api.v1.RPHealthCheckRequestKt.Dsl._create(com.nukive.renderprotocol.api.v1.RPHealthCheckRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `proto.renderprotocol.api.v1.RPHealthCheckRequest`
 */
public object RPHealthCheckRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.nukive.renderprotocol.api.v1.RPHealthCheckRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.nukive.renderprotocol.api.v1.RPHealthCheckRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.nukive.renderprotocol.api.v1.RPHealthCheckRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.nukive.renderprotocol.api.v1.RPHealthCheckRequest.copy(block: `com.nukive.renderprotocol.api.v1`.RPHealthCheckRequestKt.Dsl.() -> kotlin.Unit): com.nukive.renderprotocol.api.v1.RPHealthCheckRequest =
  `com.nukive.renderprotocol.api.v1`.RPHealthCheckRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

