// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_health_service.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.api.v1;

@com.google.protobuf.Generated
public interface RPHealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.renderprotocol.api.v1.RPHealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {
}
