// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_metadata.proto
// Protobuf Java Version: 4.35.0

package com.nukive.renderprotocol.api.v1;

/**
 * Protobuf type {@code proto.renderprotocol.api.v1.RPSessionContext}
 */
@com.google.protobuf.Generated
public final class RPSessionContext extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.renderprotocol.api.v1.RPSessionContext)
    RPSessionContextOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RPSessionContext");
  }
  // Use RPSessionContext.newBuilder() to construct.
  private RPSessionContext(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPSessionContext() {
    sessionToken_ = "";
    traceId_ = "";
    localeOverride_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nukive.renderprotocol.api.v1.RpApiMetadataProto.internal_static_proto_renderprotocol_api_v1_RPSessionContext_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nukive.renderprotocol.api.v1.RpApiMetadataProto.internal_static_proto_renderprotocol_api_v1_RPSessionContext_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nukive.renderprotocol.api.v1.RpApiMetadataProto.internal_static_proto_renderprotocol_api_v1_RPSessionContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nukive.renderprotocol.api.v1.RPSessionContext.class, com.nukive.renderprotocol.api.v1.RPSessionContext.Builder.class);
  }

  private int bitField0_;
  public static final int SESSION_TOKEN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionToken_ = "";
  /**
   * <code>string session_token = 1 [json_name = "sessionToken"];</code>
   * @return The sessionToken.
   */
  @java.lang.Override
  public java.lang.String getSessionToken() {
    java.lang.Object ref = sessionToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionToken_ = s;
      return s;
    }
  }
  /**
   * <code>string session_token = 1 [json_name = "sessionToken"];</code>
   * @return The bytes for sessionToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionTokenBytes() {
    java.lang.Object ref = sessionToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
   * @return Whether the traceId field is set.
   */
  @java.lang.Override
  public boolean hasTraceId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCALE_OVERRIDE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object localeOverride_ = "";
  /**
   * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
   * @return Whether the localeOverride field is set.
   */
  @java.lang.Override
  public boolean hasLocaleOverride() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
   * @return The localeOverride.
   */
  @java.lang.Override
  public java.lang.String getLocaleOverride() {
    java.lang.Object ref = localeOverride_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      localeOverride_ = s;
      return s;
    }
  }
  /**
   * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
   * @return The bytes for localeOverride.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocaleOverrideBytes() {
    java.lang.Object ref = localeOverride_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localeOverride_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionToken_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, traceId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, localeOverride_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionToken_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, traceId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, localeOverride_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nukive.renderprotocol.api.v1.RPSessionContext)) {
      return super.equals(obj);
    }
    com.nukive.renderprotocol.api.v1.RPSessionContext other = (com.nukive.renderprotocol.api.v1.RPSessionContext) obj;

    if (!getSessionToken()
        .equals(other.getSessionToken())) return false;
    if (hasTraceId() != other.hasTraceId()) return false;
    if (hasTraceId()) {
      if (!getTraceId()
          .equals(other.getTraceId())) return false;
    }
    if (hasLocaleOverride() != other.hasLocaleOverride()) return false;
    if (hasLocaleOverride()) {
      if (!getLocaleOverride()
          .equals(other.getLocaleOverride())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getSessionToken().hashCode();
    if (hasTraceId()) {
      hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceId().hashCode();
    }
    if (hasLocaleOverride()) {
      hash = (37 * hash) + LOCALE_OVERRIDE_FIELD_NUMBER;
      hash = (53 * hash) + getLocaleOverride().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nukive.renderprotocol.api.v1.RPSessionContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nukive.renderprotocol.api.v1.RPSessionContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.renderprotocol.api.v1.RPSessionContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.renderprotocol.api.v1.RPSessionContext)
      com.nukive.renderprotocol.api.v1.RPSessionContextOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nukive.renderprotocol.api.v1.RpApiMetadataProto.internal_static_proto_renderprotocol_api_v1_RPSessionContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nukive.renderprotocol.api.v1.RpApiMetadataProto.internal_static_proto_renderprotocol_api_v1_RPSessionContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nukive.renderprotocol.api.v1.RPSessionContext.class, com.nukive.renderprotocol.api.v1.RPSessionContext.Builder.class);
    }

    // Construct using com.nukive.renderprotocol.api.v1.RPSessionContext.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionToken_ = "";
      traceId_ = "";
      localeOverride_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nukive.renderprotocol.api.v1.RpApiMetadataProto.internal_static_proto_renderprotocol_api_v1_RPSessionContext_descriptor;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.api.v1.RPSessionContext getDefaultInstanceForType() {
      return com.nukive.renderprotocol.api.v1.RPSessionContext.getDefaultInstance();
    }

    @java.lang.Override
    public com.nukive.renderprotocol.api.v1.RPSessionContext build() {
      com.nukive.renderprotocol.api.v1.RPSessionContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nukive.renderprotocol.api.v1.RPSessionContext buildPartial() {
      com.nukive.renderprotocol.api.v1.RPSessionContext result = new com.nukive.renderprotocol.api.v1.RPSessionContext(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nukive.renderprotocol.api.v1.RPSessionContext result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionToken_ = sessionToken_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.traceId_ = traceId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.localeOverride_ = localeOverride_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nukive.renderprotocol.api.v1.RPSessionContext) {
        return mergeFrom((com.nukive.renderprotocol.api.v1.RPSessionContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nukive.renderprotocol.api.v1.RPSessionContext other) {
      if (other == com.nukive.renderprotocol.api.v1.RPSessionContext.getDefaultInstance()) return this;
      if (!other.getSessionToken().isEmpty()) {
        sessionToken_ = other.sessionToken_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasTraceId()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasLocaleOverride()) {
        localeOverride_ = other.localeOverride_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              localeOverride_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionToken_ = "";
    /**
     * <code>string session_token = 1 [json_name = "sessionToken"];</code>
     * @return The sessionToken.
     */
    public java.lang.String getSessionToken() {
      java.lang.Object ref = sessionToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_token = 1 [json_name = "sessionToken"];</code>
     * @return The bytes for sessionToken.
     */
    public com.google.protobuf.ByteString
        getSessionTokenBytes() {
      java.lang.Object ref = sessionToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_token = 1 [json_name = "sessionToken"];</code>
     * @param value The sessionToken to set.
     * @return This builder for chaining.
     */
    public Builder setSessionToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_token = 1 [json_name = "sessionToken"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionToken() {
      sessionToken_ = getDefaultInstance().getSessionToken();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_token = 1 [json_name = "sessionToken"];</code>
     * @param value The bytes for sessionToken to set.
     * @return This builder for chaining.
     */
    public Builder setSessionTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
     * @return Whether the traceId field is set.
     */
    public boolean hasTraceId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object localeOverride_ = "";
    /**
     * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
     * @return Whether the localeOverride field is set.
     */
    public boolean hasLocaleOverride() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
     * @return The localeOverride.
     */
    public java.lang.String getLocaleOverride() {
      java.lang.Object ref = localeOverride_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localeOverride_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
     * @return The bytes for localeOverride.
     */
    public com.google.protobuf.ByteString
        getLocaleOverrideBytes() {
      java.lang.Object ref = localeOverride_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localeOverride_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
     * @param value The localeOverride to set.
     * @return This builder for chaining.
     */
    public Builder setLocaleOverride(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      localeOverride_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLocaleOverride() {
      localeOverride_ = getDefaultInstance().getLocaleOverride();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string locale_override = 3 [json_name = "localeOverride"];</code>
     * @param value The bytes for localeOverride to set.
     * @return This builder for chaining.
     */
    public Builder setLocaleOverrideBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      localeOverride_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.renderprotocol.api.v1.RPSessionContext)
  }

  // @@protoc_insertion_point(class_scope:proto.renderprotocol.api.v1.RPSessionContext)
  private static final com.nukive.renderprotocol.api.v1.RPSessionContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nukive.renderprotocol.api.v1.RPSessionContext();
  }

  public static com.nukive.renderprotocol.api.v1.RPSessionContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPSessionContext>
      PARSER = new com.google.protobuf.AbstractParser<RPSessionContext>() {
    @java.lang.Override
    public RPSessionContext parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPSessionContext> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPSessionContext> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nukive.renderprotocol.api.v1.RPSessionContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

